// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceDetail } from '../../../lib/components/ResourceDetail';
import { getResource } from '../../../lib/resources';
import type { Equipment } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/equipment/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const config = getResource('equipment')!;
  return <ResourceDetail<Equipment> config={config} resourceId={resourceId} basePath="/autocrud-admin/equipment" />;
}
