// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/equipment/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('equipment')!;
  return <ResourceCreate config={config} basePath="/autocrud-admin/equipment" />;
}
