// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../lib/components/ResourceCreate';
import { getResource } from '../../../lib/resources';
import type { Equipment } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/equipment/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('equipment')!;
  return <ResourceCreate<Equipment> config={config} basePath="/autocrud-admin/equipment" />;
}
