// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceTable } from '../../../lib/components/ResourceTable';
import { getResource } from '../../../lib/resources';
import type { Equipment } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/equipment/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('equipment')!;
  return <ResourceTable<Equipment> config={config} basePath="/autocrud-admin/equipment" />;
}
