// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceDetail } from '../../../lib/components/ResourceDetail';
import { getResource } from '../../../lib/resources';
import type { GameEvent } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/game-event/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const config = getResource('game-event')!;
  return <ResourceDetail<GameEvent> config={config} resourceId={resourceId} basePath="/autocrud-admin/game-event" isJob={true} />;
}
