// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { JobEnqueue } from '../../../lib/components/JobEnqueue';
import { getResource } from '../../../lib/resources';
import type { GameEvent } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/game-event/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('game-event')!;
  return <JobEnqueue<GameEvent> config={config} basePath="/autocrud-admin/game-event" />;
}
