// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { JobTable } from '../../../autocrud/lib/components/JobTable';
import { getResource } from '../../../autocrud/lib/resources';
import type { GameEvent } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/game-event/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('game-event')!;
  return <JobTable<GameEvent> config={config} basePath="/autocrud-admin/game-event" />;
}
