// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { BackupRestore } from '../../specstar/lib/components/BackupRestore';

export const Route = createFileRoute('/specstar-admin/backup')({
  component: BackupPage,
});

function BackupPage() {
  return (
    <BackupRestore
      resourceNames={[
        'character',
        'guild',
        'skill',
        'equipment',
        'pet-job',
        'quest',
        'game-event',
        'new-char1-job',
        'create-new-character2-job',
        'create-new-character4-job',
        'pet',
      ]}
    />
  );
}
