// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Dashboard } from '../../specstar/lib/components/Dashboard';

export const Route = createFileRoute('/specstar-admin/')({
  component: Dashboard,
});
