// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { MigrationStatus } from '../../specstar/lib/components/MigrationStatus';

export const Route = createFileRoute('/specstar-admin/migrate')({
  component: MigratePage,
});

function MigratePage() {
  return (
    <MigrationStatus
      resourceNames={[
        'character',
        'guild',
        'skill',
        'equipment',
        'pet-job',
        'quest',
        'game-event',
        'new-char1-job',
        'create-new-character2-job',
        'create-new-character4-job',
        'pet',
      ]}
    />
  );
}
