// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';
import type { Job___main___Mount_____main___Dog_ } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/pet-job/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('pet-job')!;
  return <ResourceCreate<Job___main___Mount_____main___Dog_> config={config} basePath="/autocrud-admin/pet-job" />;
}
