// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { JobTable } from '../../../autocrud/lib/components/JobTable';
import { getResource } from '../../../autocrud/lib/resources';
import type { Job___main___Mount_____main___Dog_ } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/pet-job/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('pet-job')!;
  return <JobTable<Job___main___Mount_____main___Dog_> config={config} basePath="/autocrud-admin/pet-job" />;
}
