// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceDetail } from '../../../lib/components/ResourceDetail';
import { getResource } from '../../../lib/resources';
import type { Skill } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/skill/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const config = getResource('skill')!;
  return <ResourceDetail<Skill> config={config} resourceId={resourceId} basePath="/autocrud-admin/skill" />;
}
