// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../lib/components/ResourceCreate';
import { getResource } from '../../../lib/resources';
import type { Skill } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/skill/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('skill')!;
  return <ResourceCreate<Skill> config={config} basePath="/autocrud-admin/skill" />;
}
