// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceTable } from '../../../autocrud/lib/components/ResourceTable';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/skill/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('skill')!;
  return <ResourceTable config={config} basePath="/autocrud-admin/skill" />;
}
