// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceTable } from '../../../lib/components/ResourceTable';
import { getResource } from '../../../lib/resources';
import type { Skill } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/skill/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('skill')!;
  return <ResourceTable<Skill> config={config} basePath="/autocrud-admin/skill" />;
}
