/**
 * CodeGenerator — orchestrates all code generation from IR Resources.
 *
 * Takes parsed IR Resources and writes generated .ts/.tsx files.
 * TypeScript types and Zod schemas are generated by Orval (run before this).
 * This module handles: resources.ts, api clients, routes.
 */

import fs from 'node:fs';
import path from 'node:path';

import type { Resource } from '../types.js';
import type { IRBuilder } from '../ir-builder.js';
import { genResourcesConfig } from './resources-gen.js';
import { genApiClient, genApiIndex, genBackupApiClient, genMigrateApiClient } from './api-gen.js';
import {
  genListRoute,
  genCreateRoute,
  genDetailRoute,
  genBackupPage,
  genMigratePage,
  genRootIndex,
  genDashboard,
} from './routes-gen.js';

export class CodeGenerator {
  constructor(
    private resources: Resource[],
    private spec: any,
    private ROOT: string,
    private SRC: string,
    private GEN: string,
    private ROUTES: string,
    private basePath: string,
    private builder: IRBuilder,
    private orvalSchemas?: Map<string, string>,
  ) {}

  run() {
    console.log(`📦 Resources: ${this.resources.map((r) => r.name).join(', ')}\n`);
    console.log('📝 Generating files...');

    // types.ts is generated by Orval (already exists in GEN directory)
    // If Orval failed, log a warning
    if (!fs.existsSync(path.join(this.GEN, 'types.ts'))) {
      console.warn('  ⚠️  types.ts not found — Orval may have failed');
    }

    // resources.ts — resource registry with zod schemas
    this.writeFile(
      path.join(this.GEN, 'resources.ts'),
      genResourcesConfig(
        this.resources,
        this.basePath,
        this.spec,
        (r) => this.builder.getJobHiddenFields(r),
        this.orvalSchemas,
      ),
    );

    // Per-resource API clients
    for (const r of this.resources) {
      this.writeFile(path.join(this.GEN, 'api', `${r.name}Api.ts`), genApiClient(r, this.basePath));
    }
    this.writeFile(path.join(this.GEN, 'api', 'index.ts'), genApiIndex(this.resources));

    // Backup / restore
    this.writeFile(path.join(this.GEN, 'api', 'backupApi.ts'), genBackupApiClient(this.resources, this.basePath));
    this.writeFile(path.join(this.ROUTES, 'autocrud-admin', 'backup.tsx'), genBackupPage(this.resources));

    // Migrate
    this.writeFile(path.join(this.GEN, 'api', 'migrateApi.ts'), genMigrateApiClient(this.basePath));
    this.writeFile(path.join(this.ROUTES, 'autocrud-admin', 'migrate.tsx'), genMigratePage(this.resources));

    // Root / Dashboard
    this.writeFile(path.join(this.ROUTES, 'index.tsx'), genRootIndex());
    this.writeFile(path.join(this.ROUTES, 'autocrud-admin', 'index.tsx'), genDashboard());

    // Per-resource routes
    for (const r of this.resources) {
      this.writeFile(path.join(this.ROUTES, 'autocrud-admin', r.name, 'index.tsx'), genListRoute(r));
      this.writeFile(path.join(this.ROUTES, 'autocrud-admin', r.name, 'create.tsx'), genCreateRoute(r));
      this.writeFile(path.join(this.ROUTES, 'autocrud-admin', r.name, '$resourceId.tsx'), genDetailRoute(r));
    }

    const fileCount = 4 + this.resources.length * 4 + 2 + 2;
    console.log(`\n✨ Done! Generated ${fileCount} files (+ Orval types).`);
    console.log('\nNext steps:');
    console.log('  pnpm dev');
  }

  private writeFile(filePath: string, content: string) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(`  ✅ ${path.relative(this.ROOT, filePath)}`);
  }
}
