/**
 * CodeGenerator — orchestrates all code generation from IR Resources.
 *
 * Takes parsed IR Resources and writes generated .ts/.tsx files.
 * TypeScript types and Zod schemas are generated by Orval (run before this).
 * This module handles: resources.ts, api clients, routes.
 */

import fs from 'node:fs';
import path from 'node:path';

import type { Resource } from '../types.js';
import type { IRBuilder } from '../ir-builder.js';
import { genResourcesConfig } from './resources-gen.js';
import { genApiClient, genApiIndex, genBackupApiClient, genMigrateApiClient } from './api-gen.js';
import {
  genListRoute,
  genCreateRoute,
  genDetailRoute,
  genBackupPage,
  genMigratePage,
  genRootIndex,
  genDashboard,
} from './routes-gen.js';

export class CodeGenerator {
  constructor(
    private resources: Resource[],
    private spec: any,
    private ROOT: string,
    private SRC: string,
    private GEN: string,
    private ROUTES: string,
    private basePath: string,
    private builder: IRBuilder,
    private orvalSchemas?: Map<string, string>,
  ) {}

  run() {
    console.log(`📦 Resources: ${this.resources.map((r) => r.name).join(', ')}\n`);
    console.log('📝 Generating files...');

    // types.ts is generated by Orval (already exists in GEN directory)
    // If Orval failed, log a warning
    const typesPath = path.join(this.GEN, 'types.ts');
    if (!fs.existsSync(typesPath)) {
      console.warn('  ⚠️  types.ts not found — Orval may have failed');
    } else {
      // Append resource type aliases that Orval's 'zod' client doesn't produce.
      // Route and API files import e.g. `type { Character }` from types.ts.
      this.appendResourceTypeAliases(typesPath);
    }

    // resources.ts — resource registry with zod schemas
    this.writeFile(
      path.join(this.GEN, 'resources.ts'),
      genResourcesConfig(
        this.resources,
        this.basePath,
        this.spec,
        (r) => this.builder.getJobHiddenFields(r),
        this.orvalSchemas,
      ),
    );

    // Per-resource API clients
    for (const r of this.resources) {
      this.writeFile(path.join(this.GEN, 'api', `${r.name}Api.ts`), genApiClient(r, this.basePath));
    }
    this.writeFile(path.join(this.GEN, 'api', 'index.ts'), genApiIndex(this.resources));

    // Backup / restore
    this.writeFile(path.join(this.GEN, 'api', 'backupApi.ts'), genBackupApiClient(this.resources, this.basePath));
    this.writeFile(path.join(this.ROUTES, 'autocrud-admin', 'backup.tsx'), genBackupPage(this.resources));

    // Migrate
    this.writeFile(path.join(this.GEN, 'api', 'migrateApi.ts'), genMigrateApiClient(this.basePath));
    this.writeFile(path.join(this.ROUTES, 'autocrud-admin', 'migrate.tsx'), genMigratePage(this.resources));

    // Root / Dashboard
    this.writeFile(path.join(this.ROUTES, 'index.tsx'), genRootIndex());
    this.writeFile(path.join(this.ROUTES, 'autocrud-admin', 'index.tsx'), genDashboard());

    // Per-resource routes
    for (const r of this.resources) {
      this.writeFile(path.join(this.ROUTES, 'autocrud-admin', r.name, 'index.tsx'), genListRoute(r));
      this.writeFile(path.join(this.ROUTES, 'autocrud-admin', r.name, 'create.tsx'), genCreateRoute(r));
      this.writeFile(path.join(this.ROUTES, 'autocrud-admin', r.name, '$resourceId.tsx'), genDetailRoute(r));
    }

    const fileCount = 4 + this.resources.length * 4 + 2 + 2;
    console.log(`\n✨ Done! Generated ${fileCount} files (+ Orval types).`);
    console.log('\nNext steps:');
    console.log('  pnpm dev');
  }

  private writeFile(filePath: string, content: string) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(`  ✅ ${path.relative(this.ROOT, filePath)}`);
  }

  /**
   * Append `export type X = Record<string, unknown>` for each resource's
   * schemaName (and custom action bodySchemaNames) to the Orval-generated
   * types.ts so that route and API files can import them.
   *
   * Orval's 'zod' client only emits Zod schemas (export const), not
   * TypeScript interfaces.  We bridge the gap with lightweight aliases.
   */
  private appendResourceTypeAliases(typesPath: string) {
    const existing = fs.readFileSync(typesPath, 'utf-8');

    // Collect all schema names that our codegen imports
    const names = new Set<string>();
    for (const r of this.resources) {
      names.add(r.schemaName);
      if (r.customCreateActions) {
        for (const a of r.customCreateActions) {
          if (a.bodySchemaName) names.add(a.bodySchemaName);
        }
      }
    }

    // Only add types that don't already exist as exports
    const missing: string[] = [];
    for (const name of names) {
      // Check for `export type X` or `export interface X`
      const typeRegex = new RegExp(`export\\s+(?:type|interface)\\s+${name}\\b`);
      if (!typeRegex.test(existing)) {
        missing.push(name);
      }
    }

    if (missing.length === 0) return;

    const lines = [
      '',
      '// ── Resource type aliases (generated by AutoCRUD) ──────────────────────────',
      '// Orval "zod" client only produces Zod const schemas; these type aliases',
      '// allow route and API files to import properly-named TypeScript types.',
      '',
    ];
    for (const name of missing.sort()) {
      lines.push(`export type ${name} = Record<string, unknown>;`);
    }
    lines.push('');

    fs.writeFileSync(typesPath, existing + lines.join('\n'), 'utf-8');
  }
}
