/**
 * Generate the resources.ts registry file.
 */

import type { Resource } from '../types.js';
import { toCamel, serializeField } from '../types.js';
import { computeZodType, buildNestedZodFields } from './zod-type.js';

/**
 * Generate the resources config registry code.
 *
 * @param resources - Parsed IR resources
 * @param basePath - API base path
 * @param spec - Raw OpenAPI spec (for x-autocrud-async-create-jobs)
 * @param getJobHiddenFields - Function to get job hidden fields for a resource
 */
export function genResourcesConfig(
  resources: Resource[],
  basePath: string,
  spec: any,
  getJobHiddenFields: (r: Resource) => string[],
): string {
  const configs = resources.map((r) => {
    const fields = r.fields.map((f) => serializeField(f));
    const zodFields = buildNestedZodFields(r.fields);
    const displayNameLine = r.displayNameField ? `    displayNameField: '${r.displayNameField}',\n` : '';

    let customActionsBlock = '';
    if (r.customCreateActions && r.customCreateActions.length > 0) {
      const actionEntries = r.customCreateActions.map((action) => {
        const actionFields = action.fields.map((f) => serializeField(f));
        const actionZodFields = buildNestedZodFields(action.fields);
        const methodName = toCamel(action.operationId);
        const asyncLines: string[] = [];
        if (action.asyncMode) {
          asyncLines.push(`        asyncMode: '${action.asyncMode}',`);
        }
        if (action.jobResourceName) {
          asyncLines.push(`        jobResourceName: '${action.jobResourceName}',`);
        }
        const asyncBlock = asyncLines.length > 0 ? '\n' + asyncLines.join('\n') : '';
        return `      {
        name: '${action.name}',
        label: '${action.label}',
        fields: ${JSON.stringify(actionFields, null, 10).replace(/"([^"]+)":/g, '$1:')},
        zodSchema: z.object({
${actionZodFields}
        }),
        apiMethod: ${r.camel}Api.${methodName},${asyncBlock}
      }`;
      });
      customActionsBlock = `
    customCreateActions: [
${actionEntries.join(',\n')}
    ],`;
    }

    return `  '${r.name}': {
    name: '${r.name}',
    label: '${r.label}',
    pluralLabel: '${r.label}s',
${displayNameLine}    schema: '${r.schemaName}',
    fields: ${JSON.stringify(fields, null, 6).replace(/"([^"]+)":/g, '$1:')},
    zodSchema: z.object({
${zodFields}
    }),
    apiClient: ${r.camel}Api,
    maxFormDepth: ${r.maxFormDepth},${
      r.isJob
        ? `
    defaultHiddenFields: ${JSON.stringify(getJobHiddenFields(r))},`
        : ''
    }${
      r.isUnion
        ? `
    isUnion: true,`
        : ''
    }${customActionsBlock}
  }`;
  });

  const imports = resources.map((r) => `import { ${r.camel}Api } from './api/${r.name}Api';`).join('\n');

  const resourceNameUnion = resources.map((r) => `'${r.name}'`).join(' | ');
  const detailRouteUnion = resources.map((r) => `'/autocrud-admin/${r.name}/$resourceId'`).join('\n  | ');
  const listRouteUnion = resources.map((r) => `'/autocrud-admin/${r.name}'`).join('\n  | ');
  const detailRouteCases = resources
    .map((r) => `  '${r.name}': '/autocrud-admin/${r.name}/$resourceId'`)
    .join(',\n');
  const listRouteCases = resources.map((r) => `  '${r.name}': '/autocrud-admin/${r.name}'`).join(',\n');

  const fieldNameTypes = resources
    .map((r) => {
      const fieldNames = r.fields.map((f) => `'${f.name}'`).join(' | ');
      return `export type ${r.pascal}FieldName = ${fieldNames};`;
    })
    .join('\n');

  const fieldMapEntries = resources.map((r) => `  '${r.name}': ${r.pascal}FieldName;`).join('\n');

  const asyncJobsMap: Record<string, string> = spec['x-autocrud-async-create-jobs'] ?? {};
  let asyncJobsBlock = '';
  if (Object.keys(asyncJobsMap).length > 0) {
    const entries = Object.entries(asyncJobsMap)
      .map(([jobName, parentName]) => `  '${jobName}': '${parentName}'`)
      .join(',\n');
    asyncJobsBlock = `
import { asyncCreateJobs } from '../lib/resources';
Object.assign(asyncCreateJobs, {
${entries},
});
`;
  }

  return `// Auto-generated by AutoCRUD Web Generator
import { resources as registry, applyCustomizations as applyCustomizationsImpl } from '../lib/resources';
import type { ResourceCustomizations as ResourceCustomizationsBase } from '../lib/resources';
import { setApiBasePath } from '../lib/client';
import { z } from 'zod';
${imports}

// Inject API base path so blob URLs and other non-Axios URL constructions
// include the correct prefix (e.g. '/v1/autocrud/blobs/upload').
setApiBasePath('${basePath}');

/** Union type of all resource names */
export type ResourceName = ${resourceNameUnion};

/** Per-resource field name union types */
${fieldNameTypes}

/** Mapping from resource name to its field name union type */
export interface ResourceFieldMap {
${fieldMapEntries}
}

/** Type-safe customization config for all resources */
export type ResourceCustomizations = ResourceCustomizationsBase<ResourceFieldMap>;

/** Union type of all resource detail route paths */
export type ResourceDetailRoute =
  | ${detailRouteUnion};

/** Union type of all resource list route paths */
export type ResourceListRoute =
  | ${listRouteUnion};

/** Mapping from resource name to detail route path */
const detailRoutes: Record<ResourceName, ResourceDetailRoute> = {
${detailRouteCases},
};

/** Mapping from resource name to list route path */
const listRoutes: Record<ResourceName, ResourceListRoute> = {
${listRouteCases},
};

/** Get the detail route path for a resource (type-safe for TanStack Router) */
export function getResourceDetailRoute(resource: ResourceName): ResourceDetailRoute {
  return detailRoutes[resource];
}

/** Get the list route path for a resource (type-safe for TanStack Router) */
export function getResourceListRoute(resource: ResourceName): ResourceListRoute {
  return listRoutes[resource];
}

Object.assign(registry, {
${configs.join(',\n')}
});
${asyncJobsBlock}
/**
 * Apply type-safe customizations to the generated resources.
 * Call this in main.tsx after the resources are registered.
 */
export function applyCustomizations(customizations: ResourceCustomizations): void {
  applyCustomizationsImpl(customizations);
}

export { registry as resources };
`;
}
