/**
 * Tests for codegen/routes-gen.ts — Route page generation.
 */
import { describe, it, expect } from 'vitest';
import { OpenAPIParser } from '../openapi-parser.js';
import { genMigratePage, genCreateRoute, genBackupPage, genListRoute, genDetailRoute, genRootIndex, genDashboard } from './routes-gen.js';

// ─── Helpers ────────────────────────────────────────────────────────────────

function parse(spec: any, basePath = '') {
  return new OpenAPIParser(spec, basePath).parse();
}

function buildSimpleSpec(basePath = '') {
  const prefix = basePath || '';
  return {
    info: { title: 'Test', version: '1.0' },
    paths: {
      [`${prefix}/character`]: { post: { requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Character' } } } } } },
      [`${prefix}/skill`]: { post: { requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Skill' } } } } } },
    },
    components: {
      schemas: {
        Character: { type: 'object', properties: { name: { type: 'string' }, level: { type: 'integer' } }, required: ['name', 'level'] },
        Skill: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] },
      },
    },
  };
}

// ============================================================================
// genMigratePage
// ============================================================================
describe('genMigratePage', () => {
  it('generates a route page importing MigrationStatus component', () => {
    const resources = parse(buildSimpleSpec());
    const code = genMigratePage(resources);

    expect(code).toContain("import { createFileRoute } from '@tanstack/react-router'");
    expect(code).toContain("import { MigrationStatus } from '../../autocrud/lib/components/MigrationStatus'");
    expect(code).toContain("createFileRoute('/autocrud-admin/migrate')");
    expect(code).toContain('MigrationStatus');
  });

  it('passes all resource names to MigrationStatus', () => {
    const resources = parse(buildSimpleSpec());
    const code = genMigratePage(resources);

    expect(code).toContain("'character'");
    expect(code).toContain("'skill'");
    expect(code).toContain('resourceNames={[');
  });

  it('includes auto-generated comment header', () => {
    const resources = parse(buildSimpleSpec());
    const code = genMigratePage(resources);

    expect(code).toContain('// Auto-generated by AutoCRUD Web Generator');
  });
});

// ============================================================================
// genCreateRoute — Job resource
// ============================================================================
describe('genCreateRoute — Job resource', () => {
  it('generates create route for Job resource', () => {
    const spec = {
      info: { title: 'Test', version: '1.0' },
      paths: {
        '/game-event': { post: { requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/GameEvent' } } } } } },
        '/game-event/{id}': { get: {} },
      },
      components: {
        schemas: {
          GameEvent: {
            type: 'object',
            properties: {
              payload: { type: 'object' },
              status: { type: 'string', default: 'pending' },
              errmsg: { type: 'string', default: '' },
              retries: { type: 'integer', default: 0 },
              periodic_interval_seconds: { type: 'number', default: 0 },
              periodic_max_runs: { type: 'integer', default: 0 },
              periodic_runs: { type: 'integer', default: 0 },
              periodic_initial_delay_seconds: { type: 'number', default: 0 },
            },
            required: ['payload'],
          },
        },
      },
    };
    const resources = parse(spec);
    const code = genCreateRoute(resources[0]);

    expect(code).toContain("createFileRoute('/autocrud-admin/game-event/create')");
    expect(code).toContain('ResourceCreate');
  });
});

// ============================================================================
// genBackupPage
// ============================================================================
describe('genBackupPage', () => {
  it('generates backup route page', () => {
    const resources = parse(buildSimpleSpec());
    const code = genBackupPage(resources);

    expect(code).toContain("createFileRoute('/autocrud-admin/backup')");
    expect(code).toContain('BackupRestore');
  });
});

// ============================================================================
// genListRoute
// ============================================================================
describe('genListRoute', () => {
  it('generates list route for resource', () => {
    const resources = parse(buildSimpleSpec());
    const code = genListRoute(resources.find((r) => r.name === 'character')!);

    expect(code).toContain("createFileRoute('/autocrud-admin/character/')");
    expect(code).toContain('ResourceTable');
  });
});

// ============================================================================
// genDetailRoute
// ============================================================================
describe('genDetailRoute', () => {
  it('generates detail route for resource', () => {
    const resources = parse(buildSimpleSpec());
    const code = genDetailRoute(resources.find((r) => r.name === 'character')!);

    expect(code).toContain("createFileRoute('/autocrud-admin/character/$resourceId')");
    expect(code).toContain('ResourceDetail');
  });
});

// ============================================================================
// genRootIndex / genDashboard
// ============================================================================
describe('genRootIndex / genDashboard', () => {
  it('generates root index with redirect', () => {
    const code = genRootIndex();
    expect(code).toContain("createFileRoute('/')");
  });

  it('generates dashboard page', () => {
    const code = genDashboard();
    expect(code).toContain("createFileRoute('/autocrud-admin/')");
    expect(code).toContain('Dashboard');
  });
});
