/**
 * Generate route files (list, create, detail, backup, migrate, root, dashboard).
 */

import type { Resource } from '../types.js';

export function genListRoute(r: Resource): string {
  if (r.isJob) {
    return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@mantine/core';
import { JobTable } from '../../../specstar/lib/components/JobTable';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/${r.name}/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('${r.name}')!;
  return (
    <Container size="xl" py="xl">
      <JobTable config={config} basePath="/specstar-admin/${r.name}" />
    </Container>
  );
}
`;
  }

  // Check if this resource has async-create job actions
  const hasAsyncJobs = r.customCreateActions?.some((a) => a.asyncMode === 'job' && a.jobResourceName);

  if (hasAsyncJobs) {
    return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container, Stack } from '@mantine/core';
import { ResourceTable } from '../../../specstar/lib/components/ResourceTable';
import { PendingJobsAccordion } from '../../../specstar/lib/components/PendingJobsAccordion';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/${r.name}/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('${r.name}')!;
  return (
    <Container size="xl" py="xl">
      <Stack gap="md">
        <PendingJobsAccordion parentResourceName="${r.name}" />
        <ResourceTable config={config} basePath="/specstar-admin/${r.name}" />
      </Stack>
    </Container>
  );
}
`;
  }

  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@mantine/core';
import { ResourceTable } from '../../../specstar/lib/components/ResourceTable';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/${r.name}/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('${r.name}')!;
  return (
    <Container size="xl" py="xl">
      <ResourceTable config={config} basePath="/specstar-admin/${r.name}" />
    </Container>
  );
}
`;
}

export function genCreateRoute(r: Resource): string {
  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../specstar/lib/components/ResourceCreate';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/${r.name}/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('${r.name}')!;
  return <ResourceCreate config={config} basePath="/specstar-admin/${r.name}" />;
}
`;
}

export function genDetailRoute(r: Resource): string {
  // Check if this resource has async-update job actions (shown on detail page)
  const hasAsyncUpdateJobs = r.customUpdateActions?.some((a) => a.asyncMode === 'job' && a.jobResourceName);

  if (hasAsyncUpdateJobs) {
    return `// Auto-generated by SpecStar Web Generator
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { Stack } from '@mantine/core';
import { ResourceDetail } from '../../../specstar/lib/components/ResourceDetail';
import { PendingUpdateJobsAccordion } from '../../../specstar/lib/components/job/PendingUpdateJobsAccordion';
import { getResource } from '../../../specstar/lib/resources';

type DetailSearch = { revision?: string };

export const Route = createFileRoute('/specstar-admin/${r.name}/$resourceId')({
  component: DetailPage,
  validateSearch: (search: Record<string, unknown>): DetailSearch => ({
    revision: typeof search.revision === 'string' ? search.revision : undefined,
  }),
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const { revision } = Route.useSearch();
  const navigate = useNavigate({ from: '/specstar-admin/${r.name}/$resourceId' });

  const config = getResource('${r.name}')!;

  const handleRevisionChange = (rev: string | null) => {
    navigate({
      search: { revision: rev ?? undefined },
      replace: true,
    });
  };

  return (
    <Stack gap="md">
      <PendingUpdateJobsAccordion parentResourceName="${r.name}" resourceId={resourceId} />
      <ResourceDetail
        config={config}
        resourceId={resourceId}
        basePath="/specstar-admin/${r.name}"${r.isJob ? '\n        isJob={true}' : ''}
        initialRevision={revision}
        onRevisionChange={handleRevisionChange}
      />
    </Stack>
  );
}
`;
  }

  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { ResourceDetail } from '../../../specstar/lib/components/ResourceDetail';
import { getResource } from '../../../specstar/lib/resources';

type DetailSearch = { revision?: string };

export const Route = createFileRoute('/specstar-admin/${r.name}/$resourceId')({
  component: DetailPage,
  validateSearch: (search: Record<string, unknown>): DetailSearch => ({
    revision: typeof search.revision === 'string' ? search.revision : undefined,
  }),
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const { revision } = Route.useSearch();
  const navigate = useNavigate({ from: '/specstar-admin/${r.name}/$resourceId' });

  const config = getResource('${r.name}')!;

  const handleRevisionChange = (rev: string | null) => {
    navigate({
      search: { revision: rev ?? undefined },
      replace: true,
    });
  };

  return (
    <ResourceDetail
      config={config}
      resourceId={resourceId}
      basePath="/specstar-admin/${r.name}"${r.isJob ? '\n      isJob={true}' : ''}
      initialRevision={revision}
      onRevisionChange={handleRevisionChange}
    />
  );
}
`;
}

export function genBackupPage(resources: Resource[]): string {
  const resourceNames = resources.map((r) => `'${r.name}'`).join(', ');
  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { BackupRestore } from '../../specstar/lib/components/BackupRestore';

export const Route = createFileRoute('/specstar-admin/backup')({
  component: BackupPage,
});

function BackupPage() {
  return <BackupRestore resourceNames={[${resourceNames}]} />;
}
`;
}

export function genMigratePage(resources: Resource[]): string {
  const resourceNames = resources.map((r) => `'${r.name}'`).join(', ');
  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { MigrationStatus } from '../../specstar/lib/components/MigrationStatus';

export const Route = createFileRoute('/specstar-admin/migrate')({
  component: MigratePage,
});

function MigratePage() {
  return <MigrationStatus resourceNames={[${resourceNames}]} />;
}
`;
}

export function genRootIndex(): string {
  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { Container, Title, Text, Button, Stack, Paper, Group } from '@mantine/core';
import { IconArrowRight } from '@tabler/icons-react';
import { APP_TITLE, APP_LOGO } from '@/specstar/generated/branding';

export const Route = createFileRoute('/')({
  component: HomePage,
});

function HomePage() {
  return (
    <Container size="sm" style={{ marginTop: '10vh' }}>
      <Stack gap="xl">
        <Paper shadow="md" p="xl" radius="md">
          <Stack gap="lg">
            <Group gap="xs">
              <img src={APP_LOGO} alt="" width={32} height={32} />
              <Title order={1}>{APP_TITLE}</Title>
            </Group>

            <Text size="lg" c="dimmed">
              歡迎使用 {APP_TITLE} 管理介面
            </Text>

            <Text>
              這是一個由 SpecStar 後端自動生成的 React 管理介面。 點擊下方按鈕進入管理控制台。
            </Text>

            <Button
              component={Link}
              to="/specstar-admin"
              size="lg"
              rightSection={<IconArrowRight size={20} />}
            >
              進入管理控制台
            </Button>
          </Stack>
        </Paper>
      </Stack>
    </Container>
  );
}
`;
}

export function genDashboard(): string {
  return `// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Dashboard } from '../../specstar/lib/components/Dashboard';

export const Route = createFileRoute('/specstar-admin/')({
  component: Dashboard,
});
`;
}
