/**
 * Tests for codegen/routes-gen.ts — Route page generation.
 */
import { describe, it, expect } from 'vitest';
import { buildIR } from '../test-helpers.js';
import {
  genMigratePage,
  genCreateRoute,
  genBackupPage,
  genListRoute,
  genDetailRoute,
  genRootIndex,
  genDashboard,
} from './routes-gen.js';

// ─── Helpers ────────────────────────────────────────────────────────────────

function parse(spec: any, basePath = '') {
  return buildIR(spec, basePath).resources;
}

function buildSimpleSpec(basePath = '') {
  const prefix = basePath || '';
  return {
    info: { title: 'Test', version: '1.0' },
    paths: {
      [`${prefix}/character`]: {
        post: {
          requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Character' } } } },
        },
      },
      [`${prefix}/skill`]: {
        post: { requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Skill' } } } } },
      },
    },
    components: {
      schemas: {
        Character: {
          type: 'object',
          properties: { name: { type: 'string' }, level: { type: 'integer' } },
          required: ['name', 'level'],
        },
        Skill: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] },
      },
    },
  };
}

// ============================================================================
// genMigratePage
// ============================================================================
describe('genMigratePage', () => {
  it('generates a route page importing MigrationStatus component', () => {
    const resources = parse(buildSimpleSpec());
    const code = genMigratePage(resources);

    expect(code).toContain("import { createFileRoute } from '@tanstack/react-router'");
    expect(code).toContain("import { MigrationStatus } from '../../autocrud/lib/components/MigrationStatus'");
    expect(code).toContain("createFileRoute('/autocrud-admin/migrate')");
    expect(code).toContain('MigrationStatus');
  });

  it('passes all resource names to MigrationStatus', () => {
    const resources = parse(buildSimpleSpec());
    const code = genMigratePage(resources);

    expect(code).toContain("'character'");
    expect(code).toContain("'skill'");
    expect(code).toContain('resourceNames={[');
  });

  it('includes auto-generated comment header', () => {
    const resources = parse(buildSimpleSpec());
    const code = genMigratePage(resources);

    expect(code).toContain('// Auto-generated by AutoCRUD Web Generator');
  });
});

// ============================================================================
// genCreateRoute — Job resource
// ============================================================================
describe('genCreateRoute — Job resource', () => {
  it('generates create route for Job resource', () => {
    const spec = {
      info: { title: 'Test', version: '1.0' },
      paths: {
        '/game-event': {
          post: {
            requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/GameEvent' } } } },
          },
        },
        '/game-event/{id}': { get: {} },
      },
      components: {
        schemas: {
          GameEvent: {
            type: 'object',
            properties: {
              payload: { type: 'object' },
              status: { type: 'string', default: 'pending' },
              errmsg: { type: 'string', default: '' },
              retries: { type: 'integer', default: 0 },
              periodic_interval_seconds: { type: 'number', default: 0 },
              periodic_max_runs: { type: 'integer', default: 0 },
              periodic_runs: { type: 'integer', default: 0 },
              periodic_initial_delay_seconds: { type: 'number', default: 0 },
            },
            required: ['payload'],
          },
        },
      },
    };
    const resources = parse(spec);
    const code = genCreateRoute(resources[0]);

    expect(code).toContain("createFileRoute('/autocrud-admin/game-event/create')");
    expect(code).toContain('ResourceCreate');
  });
});

// ============================================================================
// genBackupPage
// ============================================================================
describe('genBackupPage', () => {
  it('generates backup route page', () => {
    const resources = parse(buildSimpleSpec());
    const code = genBackupPage(resources);

    expect(code).toContain("createFileRoute('/autocrud-admin/backup')");
    expect(code).toContain('BackupRestore');
  });
});

// ============================================================================
// genListRoute
// ============================================================================
describe('genListRoute', () => {
  it('generates list route for resource', () => {
    const resources = parse(buildSimpleSpec());
    const code = genListRoute(resources.find((r) => r.name === 'character')!);

    expect(code).toContain("createFileRoute('/autocrud-admin/character/')");
    expect(code).toContain('ResourceTable');
    expect(code).toContain('Container');
    // Should NOT include PendingJobsAccordion for plain resources
    expect(code).not.toContain('PendingJobsAccordion');
    expect(code).not.toContain('Stack');
  });

  it('generates list route with PendingJobsAccordion for resources with async-create-job actions', () => {
    const resources = parse(buildSimpleSpec());
    const charResource = resources.find((r) => r.name === 'character')!;

    // Augment with customCreateActions that have async job mode
    charResource.customCreateActions = [
      {
        name: 'create-special',
        path: '/character/create-special',
        label: 'Create Special',
        operationId: 'create_special',
        fields: [],
        asyncMode: 'job',
        jobResourceName: 'create-special-job',
      },
    ];

    const code = genListRoute(charResource);

    expect(code).toContain("createFileRoute('/autocrud-admin/character/')");
    expect(code).toContain('ResourceTable');
    expect(code).toContain('PendingJobsAccordion');
    expect(code).toContain('parentResourceName="character"');
    expect(code).toContain("import { Container, Stack } from '@mantine/core'");
    expect(code).toContain(
      "import { PendingJobsAccordion } from '../../../autocrud/lib/components/PendingJobsAccordion'",
    );
  });

  it('does NOT include PendingJobsAccordion for background async actions (no jobResourceName)', () => {
    const resources = parse(buildSimpleSpec());
    const charResource = resources.find((r) => r.name === 'character')!;

    charResource.customCreateActions = [
      {
        name: 'create-bg',
        path: '/character/create-bg',
        label: 'Create BG',
        operationId: 'create_bg',
        fields: [],
        asyncMode: 'background',
        // no jobResourceName
      },
    ];

    const code = genListRoute(charResource);

    expect(code).not.toContain('PendingJobsAccordion');
    expect(code).not.toContain('Stack');
    expect(code).toContain('Container');
  });
});

// ============================================================================
// genDetailRoute
// ============================================================================
describe('genDetailRoute', () => {
  it('generates detail route for resource', () => {
    const resources = parse(buildSimpleSpec());
    const code = genDetailRoute(resources.find((r) => r.name === 'character')!);

    expect(code).toContain("createFileRoute('/autocrud-admin/character/$resourceId')");
    expect(code).toContain('ResourceDetail');
  });
});

// ============================================================================
// genRootIndex / genDashboard
// ============================================================================
describe('genRootIndex / genDashboard', () => {
  it('generates root index with redirect', () => {
    const code = genRootIndex();
    expect(code).toContain("createFileRoute('/')");
  });

  it('generates dashboard page', () => {
    const code = genDashboard();
    expect(code).toContain("createFileRoute('/autocrud-admin/')");
    expect(code).toContain('Dashboard');
  });
});
