/**
 * Generate route files (list, create, detail, backup, migrate, root, dashboard).
 */

import type { Resource } from '../types.js';

export function genListRoute(r: Resource): string {
  if (r.isJob) {
    return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { JobTable } from '../../../autocrud/lib/components/JobTable';
import { getResource } from '../../../autocrud/lib/resources';
import type { ${r.schemaName} } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/${r.name}/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('${r.name}')!;
  return <JobTable<${r.schemaName}> config={config} basePath="/autocrud-admin/${r.name}" />;
}
`;
  }

  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceTable } from '../../../autocrud/lib/components/ResourceTable';
import { getResource } from '../../../autocrud/lib/resources';
import type { ${r.schemaName} } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/${r.name}/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('${r.name}')!;
  return <ResourceTable<${r.schemaName}> config={config} basePath="/autocrud-admin/${r.name}" />;
}
`;
}

export function genCreateRoute(r: Resource): string {
  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';
import type { ${r.schemaName} } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/${r.name}/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('${r.name}')!;
  return <ResourceCreate<${r.schemaName}> config={config} basePath="/autocrud-admin/${r.name}" />;
}
`;
}

export function genDetailRoute(r: Resource): string {
  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { ResourceDetail } from '../../../autocrud/lib/components/ResourceDetail';
import { getResource } from '../../../autocrud/lib/resources';
import type { ${r.schemaName} } from '../../../autocrud/generated/types';

type DetailSearch = { revision?: string };

export const Route = createFileRoute('/autocrud-admin/${r.name}/$resourceId')({
  component: DetailPage,
  validateSearch: (search: Record<string, unknown>): DetailSearch => ({
    revision: typeof search.revision === 'string' ? search.revision : undefined,
  }),
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const { revision } = Route.useSearch();
  const navigate = useNavigate({ from: '/autocrud-admin/${r.name}/$resourceId' });

  const config = getResource('${r.name}')!;

  const handleRevisionChange = (rev: string | null) => {
    navigate({
      search: { revision: rev ?? undefined },
      replace: true,
    });
  };

  return (
    <ResourceDetail<${r.schemaName}>
      config={config}
      resourceId={resourceId}
      basePath="/autocrud-admin/${r.name}"${r.isJob ? '\n      isJob={true}' : ''}
      initialRevision={revision}
      onRevisionChange={handleRevisionChange}
    />
  );
}
`;
}

export function genBackupPage(resources: Resource[]): string {
  const resourceNames = resources.map((r) => `'${r.name}'`).join(', ');
  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { BackupRestore } from '../../autocrud/lib/components/BackupRestore';

export const Route = createFileRoute('/autocrud-admin/backup')({
  component: BackupPage,
});

function BackupPage() {
  return <BackupRestore resourceNames={[${resourceNames}]} />;
}
`;
}

export function genMigratePage(resources: Resource[]): string {
  const resourceNames = resources.map((r) => `'${r.name}'`).join(', ');
  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { MigrationStatus } from '../../autocrud/lib/components/MigrationStatus';

export const Route = createFileRoute('/autocrud-admin/migrate')({
  component: MigratePage,
});

function MigratePage() {
  return <MigrationStatus resourceNames={[${resourceNames}]} />;
}
`;
}

export function genRootIndex(): string {
  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { Container, Title, Text, Button, Stack, Paper, Group } from '@mantine/core';
import { IconArrowRight, IconDatabase } from '@tabler/icons-react';

export const Route = createFileRoute('/')({
  component: HomePage,
});

function HomePage() {
  return (
    <Container size="sm" style={{ marginTop: '10vh' }}>
      <Stack gap="xl">
        <Paper shadow="md" p="xl" radius="md">
          <Stack gap="lg">
            <Group gap="xs">
              <IconDatabase size={32} />
              <Title order={1}>AutoCRUD Web</Title>
            </Group>

            <Text size="lg" c="dimmed">
              歡迎使用 AutoCRUD 自動化管理介面
            </Text>

            <Text>
              這是一個由 AutoCRUD 後端自動生成的 React 管理介面。 點擊下方按鈕進入管理控制台。
            </Text>

            <Button
              component={Link}
              to="/autocrud-admin"
              size="lg"
              rightSection={<IconArrowRight size={20} />}
            >
              進入管理控制台
            </Button>
          </Stack>
        </Paper>
      </Stack>
    </Container>
  );
}
`;
}

export function genDashboard(): string {
  return `// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Dashboard } from '../../autocrud/lib/components/Dashboard';

export const Route = createFileRoute('/autocrud-admin/')({
  component: Dashboard,
});
`;
}
