// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { JobTable } from '../../../autocrud/lib/components/JobTable';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/create-new-character2-job/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('create-new-character2-job')!;
  return <JobTable config={config} basePath="/autocrud-admin/create-new-character2-job" />;
}
