// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { JobTable } from '../../../autocrud/lib/components/JobTable';
import { getResource } from '../../../autocrud/lib/resources';
import type { CreateNewCharacter2CharacterJob } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/create-new-character2-job/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('create-new-character2-job')!;
  return (
    <JobTable<CreateNewCharacter2CharacterJob>
      config={config}
      basePath="/autocrud-admin/create-new-character2-job"
    />
  );
}
