// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import {
  Container, Title, Group, Button, Stack, Text, Card, Badge,
  Grid, Loader, Alert, Modal, TextInput, NumberInput, Select,
  Checkbox, Textarea, Table, ActionIcon, Tooltip,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconEdit, IconTrash, IconArrowLeft, IconHistory, IconRestore } from '@tabler/icons-react';
import { gameEventApi } from '../../generated/api/game-eventApi';
import type { GameEvent } from '../../generated/types';
import type { FullResource, RevisionInfo } from '../../types/api';

export const Route = createFileRoute('/game-event/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const [res, setRes] = useState<FullResource<GameEvent> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editOpen, { open: openEdit, close: closeEdit }] = useDisclosure(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [ed, setEd] = useState<Record<string, any>>({});
  const [saving, setSaving] = useState(false);
  const [revisions, setRevisions] = useState<RevisionInfo[]>([]);
  const [showRev, { toggle: toggleRev }] = useDisclosure(false);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const r = await gameEventApi.getFull(resourceId);
      setRes(r.data);
      setEd({ ...(r.data.data as Record<string, unknown>) });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [resourceId]);

  const handleUpdate = async () => {
    setSaving(true);
    try {
      await gameEventApi.update(resourceId, ed as unknown as GameEvent);
      closeEdit();
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Update failed');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm('Delete this resource?')) return;
    try {
      await gameEventApi.delete(resourceId);
      window.history.back();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Delete failed');
    }
  };

  const handleRestore = async () => {
    try {
      await gameEventApi.restore(resourceId);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Restore failed');
    }
  };

  const loadRevisions = async () => {
    try {
      const r = await gameEventApi.revisionList(resourceId);
      setRevisions(r.data.revisions);
    } catch (e) { console.error(e); }
  };

  if (loading) return <Container size="lg" py="xl"><Loader /></Container>;
  if (error || !res) return <Container size="lg" py="xl"><Alert color="red" title="Error">{error || 'Not found'}</Alert></Container>;

  const { data, meta, revision_info } = res;

  return (
    <Container size="lg" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <Group>
            <Button variant="subtle" component={Link} to="/game-event" leftSection={<IconArrowLeft size={16} />}>Back</Button>
            <Title order={2}>Game Event</Title>
            <Badge color={revision_info.status === 'stable' ? 'green' : 'yellow'}>{revision_info.status}</Badge>
          </Group>
          <Group>
            {meta.is_deleted && <Button color="green" leftSection={<IconRestore size={16} />} onClick={handleRestore}>Restore</Button>}
            <Button variant="light" leftSection={<IconHistory size={16} />} onClick={() => { toggleRev(); if (!showRev) loadRevisions(); }}>Revisions</Button>
            <Button variant="light" leftSection={<IconEdit size={16} />} onClick={openEdit}>Edit</Button>
            <Button color="red" variant="light" leftSection={<IconTrash size={16} />} onClick={handleDelete}>Delete</Button>
          </Group>
        </Group>

        {meta.is_deleted && <Alert color="red" title="Deleted">This resource has been deleted.</Alert>}

        <Grid>
          <Grid.Col span={{ base: 12, md: 8 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Data</Title>
              <Stack gap="sm">
              <div><Text size="sm" fw={500} c="dimmed">Payload</Text><Text>{data.payload != null ? String(data.payload) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Status</Text><Text>{data.status != null ? String(data.status) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Errmsg</Text><Text>{data.errmsg != null ? String(data.errmsg) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Retries</Text><Text>{data.retries != null ? String(data.retries) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Periodic Interval Seconds</Text><Text>{data.periodic_interval_seconds != null ? String(data.periodic_interval_seconds) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Periodic Max Runs</Text><Text>{data.periodic_max_runs != null ? String(data.periodic_max_runs) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Periodic Runs</Text><Text>{data.periodic_runs != null ? String(data.periodic_runs) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Periodic Initial Delay Seconds</Text><Text>{data.periodic_initial_delay_seconds != null ? String(data.periodic_initial_delay_seconds) : '-'}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
          <Grid.Col span={{ base: 12, md: 4 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Metadata</Title>
              <Stack gap="xs">
                <div><Text size="sm" fw={500} c="dimmed">Resource ID</Text><Text size="sm" style={{ wordBreak: 'break-all' }}>{meta.resource_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Revision</Text><Text size="sm">{meta.current_revision_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Total Revisions</Text><Badge>{meta.total_revision_count}</Badge></div>
                <div><Text size="sm" fw={500} c="dimmed">Created</Text><Text size="sm">{new Date(meta.created_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Updated</Text><Text size="sm">{new Date(meta.updated_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Created By</Text><Text size="sm">{meta.created_by}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
        </Grid>

        {showRev && (
          <Card shadow="sm" padding="lg" radius="md" withBorder>
            <Title order={4} mb="md">Revision History</Title>
            <Table striped highlightOnHover>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th>Revision ID</Table.Th>
                  <Table.Th>Status</Table.Th>
                  <Table.Th>Schema Ver</Table.Th>
                  <Table.Th>Hash</Table.Th>
                  <Table.Th>Action</Table.Th>
                </Table.Tr>
              </Table.Thead>
              <Table.Tbody>
                {revisions.map((rev) => (
                  <Table.Tr key={rev.uid}>
                    <Table.Td>{rev.revision_id}</Table.Td>
                    <Table.Td><Badge color={rev.status === 'stable' ? 'green' : 'yellow'}>{rev.status}</Badge></Table.Td>
                    <Table.Td>{rev.schema_version || '-'}</Table.Td>
                    <Table.Td><Text size="xs" ff="monospace">{rev.data_hash.slice(0, 12)}...</Text></Table.Td>
                    <Table.Td>
                      <Tooltip label="Switch to revision">
                        <ActionIcon variant="light" size="sm" onClick={async () => { await gameEventApi.switchRevision(resourceId, rev.revision_id); await load(); await loadRevisions(); }}>
                          <IconRestore size={14} />
                        </ActionIcon>
                      </Tooltip>
                    </Table.Td>
                  </Table.Tr>
                ))}
              </Table.Tbody>
            </Table>
          </Card>
        )}

        <Modal opened={editOpen} onClose={closeEdit} title="Edit Game Event" size="lg">
          <Stack gap="md">
            <TextInput label="Payload" value={(ed.payload ?? '') as string} onChange={(e) => setEd(p => ({ ...p, payload: e.currentTarget.value }))} required />
            <Select label="Status" data={["completed", "failed", "pending", "processing"]} value={ed.status as string ?? ''} onChange={(v) => setEd(p => ({ ...p, status: v ?? '' }))} />
            <TextInput label="Errmsg" value={(ed.errmsg ?? '') as string} onChange={(e) => setEd(p => ({ ...p, errmsg: e.currentTarget.value }))} />
            <NumberInput label="Retries" value={ed.retries as number ?? 0} onChange={(v) => setEd(p => ({ ...p, retries: Number(v) }))} />
            <NumberInput label="Periodic Interval Seconds" value={ed.periodic_interval_seconds as number ?? 0} onChange={(v) => setEd(p => ({ ...p, periodic_interval_seconds: Number(v) }))} />
            <NumberInput label="Periodic Max Runs" value={ed.periodic_max_runs as number ?? 0} onChange={(v) => setEd(p => ({ ...p, periodic_max_runs: Number(v) }))} />
            <NumberInput label="Periodic Runs" value={ed.periodic_runs as number ?? 0} onChange={(v) => setEd(p => ({ ...p, periodic_runs: Number(v) }))} />
            <NumberInput label="Periodic Initial Delay Seconds" value={ed.periodic_initial_delay_seconds as number ?? 0} onChange={(v) => setEd(p => ({ ...p, periodic_initial_delay_seconds: Number(v) }))} />
            <Group justify="flex-end">
              <Button variant="light" onClick={closeEdit}>Cancel</Button>
              <Button onClick={handleUpdate} loading={saving}>Save</Button>
            </Group>
          </Stack>
        </Modal>
      </Stack>
    </Container>
  );
}
