// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, useNavigate, Link } from '@tanstack/react-router';
import { useState } from 'react';
import {
  Container, Title, Group, Button, Stack, TextInput, NumberInput,
  Select, Checkbox, Textarea, Card, Alert,
} from '@mantine/core';
import { IconArrowLeft } from '@tabler/icons-react';
import { gameEventApi } from '../../generated/api/game-eventApi';
import type { GameEvent } from '../../generated/types';

export const Route = createFileRoute('/game-event/create')({
  component: CreatePage,
});

function CreatePage() {
  const navigate = useNavigate();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [fd, setFd] = useState<Record<string, any>>({"payload":"","status":"","errmsg":"","retries":0,"periodic_interval_seconds":0,"periodic_max_runs":0,"periodic_runs":0,"periodic_initial_delay_seconds":0});
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const result = await gameEventApi.create(fd as unknown as GameEvent);
      navigate({ to: '/game-event/$resourceId', params: { resourceId: result.data.resource_id } });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to create');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Container size="md" py="xl">
      <Stack gap="md">
        <Group>
          <Button variant="subtle" component={Link} to="/game-event" leftSection={<IconArrowLeft size={16} />}>Back</Button>
          <Title order={2}>Create Game Event</Title>
        </Group>
        {error && <Alert color="red" title="Error">{error}</Alert>}
        <Card shadow="sm" padding="lg" radius="md" withBorder>
          <Stack gap="md">
        <TextInput label="Payload" value={(fd.payload ?? '') as string} onChange={(e) => setFd(p => ({ ...p, payload: e.currentTarget.value }))} required />
        <Select label="Status" data={["completed", "failed", "pending", "processing"]} value={fd.status as string} onChange={(v) => setFd(p => ({ ...p, status: v ?? '' }))} />
        <TextInput label="Errmsg" value={(fd.errmsg ?? '') as string} onChange={(e) => setFd(p => ({ ...p, errmsg: e.currentTarget.value }))} />
        <NumberInput label="Retries" value={fd.retries as number} onChange={(v) => setFd(p => ({ ...p, retries: Number(v) }))} />
        <NumberInput label="Periodic Interval Seconds" value={fd.periodic_interval_seconds as number} onChange={(v) => setFd(p => ({ ...p, periodic_interval_seconds: Number(v) }))} />
        <NumberInput label="Periodic Max Runs" value={fd.periodic_max_runs as number} onChange={(v) => setFd(p => ({ ...p, periodic_max_runs: Number(v) }))} />
        <NumberInput label="Periodic Runs" value={fd.periodic_runs as number} onChange={(v) => setFd(p => ({ ...p, periodic_runs: Number(v) }))} />
        <NumberInput label="Periodic Initial Delay Seconds" value={fd.periodic_initial_delay_seconds as number} onChange={(v) => setFd(p => ({ ...p, periodic_initial_delay_seconds: Number(v) }))} />
            <Group justify="flex-end" mt="md">
              <Button variant="light" component={Link} to="/game-event">Cancel</Button>
              <Button onClick={handleSubmit} loading={submitting}>Create</Button>
            </Group>
          </Stack>
        </Card>
      </Stack>
    </Container>
  );
}
