// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useEffect, useState, useMemo, useCallback } from 'react';
import { Container, Title, Group, Button, Stack, Text } from '@mantine/core';
import { IconPlus, IconRefresh } from '@tabler/icons-react';
import {
  MantineReactTable, useMantineReactTable,
  type MRT_ColumnDef, type MRT_PaginationState, type MRT_SortingState,
} from 'mantine-react-table';
import { gameEventApi } from '../../generated/api/game-eventApi';
import type { GameEvent } from '../../generated/types';
import type { FullResource } from '../../types/api';

type Row = FullResource<GameEvent>;

export const Route = createFileRoute('/game-event/')({
  component: ListPage,
});

function ListPage() {
  const navigate = useNavigate();
  const [data, setData] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState<MRT_PaginationState>({ pageIndex: 0, pageSize: 20 });
  const [sorting, setSorting] = useState<MRT_SortingState>([]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const sorts = sorting.length
        ? JSON.stringify(sorting.map(s => ({ type: 'data', field_path: s.id, direction: s.desc ? '-' : '+' })))
        : undefined;
      const [list, cnt] = await Promise.all([
        gameEventApi.listFull({
          limit: pagination.pageSize,
          offset: pagination.pageIndex * pagination.pageSize,
          sorts,
        }),
        gameEventApi.count(),
      ]);
      setData(list.data);
      setTotal(cnt.data);
    } catch (e) {
      console.error('fetch error', e);
    } finally {
      setLoading(false);
    }
  }, [pagination, sorting]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const columns = useMemo<MRT_ColumnDef<Row>[]>(() => [
    {
      id: 'resource_id',
      header: 'Resource ID',
      accessorFn: (row: Row) => row?.meta?.resource_id,
      size: 220,
    },
    {
      id: 'status',
      header: 'Status',
      accessorFn: (row: Row) => row?.data?.status,
    },
    {
      id: 'errmsg',
      header: 'Errmsg',
      accessorFn: (row: Row) => row?.data?.errmsg,
    },
    {
      id: 'retries',
      header: 'Retries',
      accessorFn: (row: Row) => row?.data?.retries,
    },
    {
      id: 'periodic_interval_seconds',
      header: 'Periodic Interval Seconds',
      accessorFn: (row: Row) => row?.data?.periodic_interval_seconds,
    },
    {
      id: 'periodic_max_runs',
      header: 'Periodic Max Runs',
      accessorFn: (row: Row) => row?.data?.periodic_max_runs,
    },
    {
      id: 'periodic_runs',
      header: 'Periodic Runs',
      accessorFn: (row: Row) => row?.data?.periodic_runs,
    },
    {
      id: 'periodic_initial_delay_seconds',
      header: 'Periodic Initial Delay Seconds',
      accessorFn: (row: Row) => row?.data?.periodic_initial_delay_seconds,
    },
    {
      id: 'updated_time',
      header: 'Updated',
      accessorFn: (row: Row) => row?.meta?.updated_time,
      Cell: ({ cell }) => new Date(cell.getValue<string>()).toLocaleString(),
    },
  ], []);

  const table = useMantineReactTable({
    columns,
    data,
    manualPagination: true,
    manualSorting: true,
    rowCount: total,
    state: { isLoading: loading, pagination, sorting },
    onPaginationChange: setPagination,
    onSortingChange: setSorting,
    mantineTableBodyRowProps: ({ row }) => ({
      onClick: () => navigate({
        to: '/game-event/$resourceId',
        params: { resourceId: row.original?.meta?.resource_id ?? '' },
      }),
      style: { cursor: 'pointer' },
    }),
    initialState: { density: 'xs' },
  });

  return (
    <Container size="xl" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <div>
            <Title order={2}>Game Event</Title>
            <Text c="dimmed" size="sm">{total} total resources</Text>
          </div>
          <Group>
            <Button variant="light" leftSection={<IconRefresh size={16} />} onClick={fetchData}>Refresh</Button>
            <Button leftSection={<IconPlus size={16} />} component={Link} to="/game-event/create">Create</Button>
          </Group>
        </Group>
        <MantineReactTable table={table} />
      </Stack>
    </Container>
  );
}
