// Auto-generated by SpecStar Web Generator
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { ResourceDetail } from '../../../specstar/lib/components/ResourceDetail';
import { getResource } from '../../../specstar/lib/resources';

type DetailSearch = { revision?: string };

export const Route = createFileRoute('/specstar-admin/create-new-character4-job/$resourceId')({
  component: DetailPage,
  validateSearch: (search: Record<string, unknown>): DetailSearch => ({
    revision: typeof search.revision === 'string' ? search.revision : undefined,
  }),
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const { revision } = Route.useSearch();
  const navigate = useNavigate({ from: '/specstar-admin/create-new-character4-job/$resourceId' });

  const config = getResource('create-new-character4-job')!;

  const handleRevisionChange = (rev: string | null) => {
    navigate({
      search: { revision: rev ?? undefined },
      replace: true,
    });
  };

  return (
    <ResourceDetail
      config={config}
      resourceId={resourceId}
      basePath="/specstar-admin/create-new-character4-job"
      isJob={true}
      initialRevision={revision}
      onRevisionChange={handleRevisionChange}
    />
  );
}
