/**
 * App Branding Resolution
 *
 * The generated app is the *developer's* admin console, not SpecStar's, so its
 * name and logo are configurable. Three sources, highest priority first:
 *
 *   1. `.specstarrc.json`  — explicit per-project override (tracked, hand-edited)
 *   2. OpenAPI `info.title` — whatever the backend already calls itself
 *   3. SpecStar defaults    — fallback so a fresh scaffold still looks finished
 *
 * The resolved values are emitted into `src/specstar/generated/branding.ts`
 * (consumed by the React app) and stamped into `index.html` (which the browser
 * reads before React boots).
 */

/** Shown in the browser tab and the admin header when nothing else is set. */
export const DEFAULT_APP_TITLE = 'SpecStar Admin';

/** Served from the app's `public/` directory. */
export const DEFAULT_APP_LOGO = '/specstar-mark.svg';

/**
 * FastAPI stamps this title on every app whose author never set one, so it
 * carries no information and must not beat the SpecStar default.
 */
const PLACEHOLDER_SPEC_TITLES = new Set(['fastapi']);

/** Branding overrides read from `.specstarrc.json`. */
export interface BrandingOverrides {
  title?: string;
  logo?: string;
}

/** Fully resolved branding — every field has a usable value. */
export interface Branding {
  title: string;
  logo: string;
}

export interface ResolveBrandingInput {
  /** Overrides from `.specstarrc.json`. */
  rc?: BrandingOverrides;
  /** `info.title` from the backend's OpenAPI spec. */
  specTitle?: string;
}

/**
 * Collapse a possibly-absent, possibly-blank config value to either a usable
 * string or `undefined`. A blank string is *present but meaningless* — honoring
 * it would leave the browser tab nameless.
 */
function usable(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

export function resolveBranding(input: ResolveBrandingInput): Branding {
  const specTitle = usable(input.specTitle);
  const meaningfulSpecTitle =
    specTitle && !PLACEHOLDER_SPEC_TITLES.has(specTitle.toLowerCase()) ? specTitle : undefined;

  return {
    title: usable(input.rc?.title) ?? meaningfulSpecTitle ?? DEFAULT_APP_TITLE,
    logo: usable(input.rc?.logo) ?? DEFAULT_APP_LOGO,
  };
}

// ---------------------------------------------------------------------------
// Generated module
// ---------------------------------------------------------------------------

/** Escape a value for embedding in a single-quoted TypeScript string literal. */
function toTsLiteral(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * Render `src/specstar/generated/branding.ts` — the single place the React app
 * reads its own name and logo from.
 */
export function renderBrandingModule(branding: Branding): string {
  return `// Auto-generated by SpecStar Web Generator — do not edit.
// Override these by setting "title" / "logo" in .specstarrc.json.

/** Display name for this admin console. */
export const APP_TITLE = ${toTsLiteral(branding.title)};

/** Path to the logo asset, served from the app's public/ directory. */
export const APP_LOGO = ${toTsLiteral(branding.logo)};
`;
}

// ---------------------------------------------------------------------------
// index.html
// ---------------------------------------------------------------------------

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Any `<link>` tag whose `rel` names it an icon (`icon`, `shortcut icon`, …). */
const ICON_LINK_RE = /<link\b[^>]*\brel=(["'])[^"']*\bicon\b[^"']*\1[^>]*>/gi;
const TITLE_RE = /<title>[\s\S]*?<\/title>/i;
const HREF_RE = /\bhref=(["'])[^"']*\1/i;
const TYPE_RE = /\btype=(["'])[^"']*\1/i;

/** MIME type for a favicon path, or `undefined` when the extension is unknown. */
function faviconMimeType(logoPath: string): string | undefined {
  const ext = logoPath.split('?')[0].split('#')[0].split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'svg':
      return 'image/svg+xml';
    case 'png':
      return 'image/png';
    case 'ico':
      return 'image/x-icon';
    case 'gif':
      return 'image/gif';
    case 'jpg':
    case 'jpeg':
      return 'image/jpeg';
    case 'webp':
      return 'image/webp';
    default:
      return undefined;
  }
}

/**
 * Stamp the resolved branding into an `index.html` document.
 *
 * Only rewrites tags that are already there — this never *adds* a `<title>` or
 * favicon link, so running it against a project that deliberately dropped one
 * leaves that decision alone. Rewriting in place also makes it idempotent.
 */
export function patchIndexHtml(html: string, branding: Branding): string {
  let out = html.replace(TITLE_RE, `<title>${escapeHtml(branding.title)}</title>`);

  const mime = faviconMimeType(branding.logo);
  out = out.replace(ICON_LINK_RE, (tag) => {
    let patched = tag.replace(HREF_RE, `href="${escapeHtml(branding.logo)}"`);
    // A stale `type` (e.g. image/svg+xml on a .png) is worse than none at all.
    if (TYPE_RE.test(patched)) {
      patched = mime
        ? patched.replace(TYPE_RE, `type="${mime}"`)
        : patched.replace(TYPE_RE, '').replace(/\s{2,}/g, ' ');
    }
    return patched;
  });

  return out;
}
