// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@mantine/core';
import { JobTable } from '../../../specstar/lib/components/JobTable';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/new-char1-job/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('new-char1-job')!;
  return (
    <Container size="xl" py="xl">
      <JobTable config={config} basePath="/specstar-admin/new-char1-job" />
    </Container>
  );
}
