// Auto-generated by SpecStar Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { Container, Title, Text, Button, Stack, Paper, Group } from '@mantine/core';
import { IconArrowRight } from '@tabler/icons-react';
import { APP_TITLE, APP_LOGO } from '@/specstar/generated/branding';

export const Route = createFileRoute('/')({
  component: HomePage,
});

function HomePage() {
  return (
    <Container size="sm" style={{ marginTop: '10vh' }}>
      <Stack gap="xl">
        <Paper shadow="md" p="xl" radius="md">
          <Stack gap="lg">
            <Group gap="xs">
              <img src={APP_LOGO} alt="" width={32} height={32} />
              <Title order={1}>{APP_TITLE}</Title>
            </Group>

            <Text size="lg" c="dimmed">
              歡迎使用 {APP_TITLE} 管理介面
            </Text>

            <Text>
              這是一個由 SpecStar 後端自動生成的 React 管理介面。 點擊下方按鈕進入管理控制台。
            </Text>

            <Button
              component={Link}
              to="/specstar-admin"
              size="lg"
              rightSection={<IconArrowRight size={20} />}
            >
              進入管理控制台
            </Button>
          </Stack>
        </Paper>
      </Stack>
    </Container>
  );
}
