// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@mantine/core';
import { JobTable } from '../../../autocrud/lib/components/JobTable';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/game-event/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('game-event')!;
  return (
    <Container size="xl" py="xl">
      <JobTable config={config} basePath="/autocrud-admin/game-event" />
    </Container>
  );
}
