// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { BackupRestore } from '../../lib/components/BackupRestore';

export const Route = createFileRoute('/autocrud-admin/backup')({
  component: BackupPage,
});

function BackupPage() {
  return <BackupRestore resourceNames={['character', 'guild', 'skill', 'equipment', 'game-event']} />;
}
