// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { BackupRestore } from '../../autocrud/lib/components/BackupRestore';

export const Route = createFileRoute('/autocrud-admin/backup')({
  component: BackupPage,
});

function BackupPage() {
  return <BackupRestore resourceNames={['character', 'guild', 'skill', 'equipment', 'pet-job', 'game-event', 'new-char1-job', 'create-new-character2-job', 'create-new-character4-job', 'pet']} />;
}
