// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Dashboard } from '../../lib/components/Dashboard';

export const Route = createFileRoute('/autocrud-admin/')({
  component: Dashboard,
});
