// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { MigrationStatus } from '../../autocrud/lib/components/MigrationStatus';

export const Route = createFileRoute('/autocrud-admin/migrate')({
  component: MigratePage,
});

function MigratePage() {
  return <MigrationStatus resourceNames={['character', 'guild', 'skill', 'equipment', 'pet-job', 'game-event', 'new-char1-job', 'create-new-character2-job', 'create-new-character4-job', 'pet']} />;
}
