// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { MigrationStatus } from '../../lib/components/MigrationStatus';

export const Route = createFileRoute('/autocrud-admin/migrate')({
  component: MigratePage,
});

function MigratePage() {
  return (
    <MigrationStatus
      resourceNames={['character', 'guild', 'skill', 'equipment', 'pet-job', 'game-event', 'pet']}
    />
  );
}
