// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceDetail } from '../../../lib/components/ResourceDetail';
import { getResource } from '../../../lib/resources';
import type { Character } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/character/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const config = getResource('character')!;
  return <ResourceDetail<Character> config={config} resourceId={resourceId} basePath="/autocrud-admin/character" />;
}
