// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../lib/components/ResourceCreate';
import { getResource } from '../../../lib/resources';
import type { Character } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/character/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('character')!;
  return <ResourceCreate<Character> config={config} basePath="/autocrud-admin/character" />;
}
