// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceTable } from '../../../lib/components/ResourceTable';
import { getResource } from '../../../lib/resources';
import type { Character } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/character/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('character')!;
  return <ResourceTable<Character> config={config} basePath="/autocrud-admin/character" />;
}
