// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container, Stack } from '@mantine/core';
import { ResourceTable } from '../../../autocrud/lib/components/ResourceTable';
import { PendingJobsAccordion } from '../../../autocrud/lib/components/PendingJobsAccordion';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/character/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('character')!;
  return (
    <Container size="xl" py="xl">
      <Stack gap="md">
        <PendingJobsAccordion parentResourceName="character" />
        <ResourceTable config={config} basePath="/autocrud-admin/character" />
      </Stack>
    </Container>
  );
}
