// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import {
  Container, Title, Group, Button, Stack, Text, Card, Badge,
  Grid, Loader, Alert, Modal, TextInput, NumberInput, Select,
  Checkbox, Textarea, Table, ActionIcon, Tooltip,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconEdit, IconTrash, IconArrowLeft, IconHistory, IconRestore } from '@tabler/icons-react';
import { characterApi } from '../../generated/api/characterApi';
import type { Character } from '../../generated/types';
import type { FullResource, RevisionInfo } from '../../types/api';

export const Route = createFileRoute('/character/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const [res, setRes] = useState<FullResource<Character> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editOpen, { open: openEdit, close: closeEdit }] = useDisclosure(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [ed, setEd] = useState<Record<string, any>>({});
  const [saving, setSaving] = useState(false);
  const [revisions, setRevisions] = useState<RevisionInfo[]>([]);
  const [showRev, { toggle: toggleRev }] = useDisclosure(false);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const r = await characterApi.getFull(resourceId);
      setRes(r.data);
      setEd({ ...(r.data.data as Record<string, unknown>) });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [resourceId]);

  const handleUpdate = async () => {
    setSaving(true);
    try {
      await characterApi.update(resourceId, ed as unknown as Character);
      closeEdit();
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Update failed');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm('Delete this resource?')) return;
    try {
      await characterApi.delete(resourceId);
      window.history.back();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Delete failed');
    }
  };

  const handleRestore = async () => {
    try {
      await characterApi.restore(resourceId);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Restore failed');
    }
  };

  const loadRevisions = async () => {
    try {
      const r = await characterApi.revisionList(resourceId);
      setRevisions(r.data.revisions);
    } catch (e) { console.error(e); }
  };

  if (loading) return <Container size="lg" py="xl"><Loader /></Container>;
  if (error || !res) return <Container size="lg" py="xl"><Alert color="red" title="Error">{error || 'Not found'}</Alert></Container>;

  const { data, meta, revision_info } = res;

  return (
    <Container size="lg" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <Group>
            <Button variant="subtle" component={Link} to="/character" leftSection={<IconArrowLeft size={16} />}>Back</Button>
            <Title order={2}>Character</Title>
            <Badge color={revision_info.status === 'stable' ? 'green' : 'yellow'}>{revision_info.status}</Badge>
          </Group>
          <Group>
            {meta.is_deleted && <Button color="green" leftSection={<IconRestore size={16} />} onClick={handleRestore}>Restore</Button>}
            <Button variant="light" leftSection={<IconHistory size={16} />} onClick={() => { toggleRev(); if (!showRev) loadRevisions(); }}>Revisions</Button>
            <Button variant="light" leftSection={<IconEdit size={16} />} onClick={openEdit}>Edit</Button>
            <Button color="red" variant="light" leftSection={<IconTrash size={16} />} onClick={handleDelete}>Delete</Button>
          </Group>
        </Group>

        {meta.is_deleted && <Alert color="red" title="Deleted">This resource has been deleted.</Alert>}

        <Grid>
          <Grid.Col span={{ base: 12, md: 8 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Data</Title>
              <Stack gap="sm">
              <div><Text size="sm" fw={500} c="dimmed">Name</Text><Text>{data.name != null ? String(data.name) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Character Class</Text><Text>{data.character_class != null ? String(data.character_class) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">ValueAD X</Text><Text>{data.valueAD__x != null ? String(data.valueAD__x) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Level</Text><Text>{data.level != null ? String(data.level) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Hp</Text><Text>{data.hp != null ? String(data.hp) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Mp</Text><Text>{data.mp != null ? String(data.mp) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Attack</Text><Text>{data.attack != null ? String(data.attack) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Defense</Text><Text>{data.defense != null ? String(data.defense) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Experience</Text><Text>{data.experience != null ? String(data.experience) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Gold</Text><Text>{data.gold != null ? String(data.gold) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Guild Id</Text><Text>{data.guild_id != null ? String(data.guild_id) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Guild Name</Text><Text>{data.guild_name != null ? String(data.guild_name) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Special Ability</Text><Text>{data.special_ability != null ? String(data.special_ability) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Equipments</Text><Group gap="xs">{(data.equipments || []).map((v: string, i: number) => <Badge key={i} variant="light">{String(v)}</Badge>)}</Group></div>
              <div><Text size="sm" fw={500} c="dimmed">Created At</Text><Text>{data.created_at != null ? String(data.created_at) : '-'}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
          <Grid.Col span={{ base: 12, md: 4 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Metadata</Title>
              <Stack gap="xs">
                <div><Text size="sm" fw={500} c="dimmed">Resource ID</Text><Text size="sm" style={{ wordBreak: 'break-all' }}>{meta.resource_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Revision</Text><Text size="sm">{meta.current_revision_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Total Revisions</Text><Badge>{meta.total_revision_count}</Badge></div>
                <div><Text size="sm" fw={500} c="dimmed">Created</Text><Text size="sm">{new Date(meta.created_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Updated</Text><Text size="sm">{new Date(meta.updated_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Created By</Text><Text size="sm">{meta.created_by}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
        </Grid>

        {showRev && (
          <Card shadow="sm" padding="lg" radius="md" withBorder>
            <Title order={4} mb="md">Revision History</Title>
            <Table striped highlightOnHover>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th>Revision ID</Table.Th>
                  <Table.Th>Status</Table.Th>
                  <Table.Th>Schema Ver</Table.Th>
                  <Table.Th>Hash</Table.Th>
                  <Table.Th>Action</Table.Th>
                </Table.Tr>
              </Table.Thead>
              <Table.Tbody>
                {revisions.map((rev) => (
                  <Table.Tr key={rev.uid}>
                    <Table.Td>{rev.revision_id}</Table.Td>
                    <Table.Td><Badge color={rev.status === 'stable' ? 'green' : 'yellow'}>{rev.status}</Badge></Table.Td>
                    <Table.Td>{rev.schema_version || '-'}</Table.Td>
                    <Table.Td><Text size="xs" ff="monospace">{rev.data_hash.slice(0, 12)}...</Text></Table.Td>
                    <Table.Td>
                      <Tooltip label="Switch to revision">
                        <ActionIcon variant="light" size="sm" onClick={async () => { await characterApi.switchRevision(resourceId, rev.revision_id); await load(); await loadRevisions(); }}>
                          <IconRestore size={14} />
                        </ActionIcon>
                      </Tooltip>
                    </Table.Td>
                  </Table.Tr>
                ))}
              </Table.Tbody>
            </Table>
          </Card>
        )}

        <Modal opened={editOpen} onClose={closeEdit} title="Edit Character" size="lg">
          <Stack gap="md">
            <TextInput label="Name" value={(ed.name ?? '') as string} onChange={(e) => setEd(p => ({ ...p, name: e.currentTarget.value }))} required />
            <Select label="Character Class" data={["⚔️ 戰士", "🏹 弓箭手", "💾 數據守護者", "🔮 法師"]} value={ed.character_class as string ?? ''} onChange={(v) => setEd(p => ({ ...p, character_class: v ?? '' }))} required />
            <NumberInput label="ValueAD X" value={ed.valueAD__x as number ?? 0} onChange={(v) => setEd(p => ({ ...p, valueAD__x: Number(v) }))} />
            <NumberInput label="Level" value={ed.level as number ?? 0} onChange={(v) => setEd(p => ({ ...p, level: Number(v) }))} />
            <NumberInput label="Hp" value={ed.hp as number ?? 0} onChange={(v) => setEd(p => ({ ...p, hp: Number(v) }))} />
            <NumberInput label="Mp" value={ed.mp as number ?? 0} onChange={(v) => setEd(p => ({ ...p, mp: Number(v) }))} />
            <NumberInput label="Attack" value={ed.attack as number ?? 0} onChange={(v) => setEd(p => ({ ...p, attack: Number(v) }))} />
            <NumberInput label="Defense" value={ed.defense as number ?? 0} onChange={(v) => setEd(p => ({ ...p, defense: Number(v) }))} />
            <NumberInput label="Experience" value={ed.experience as number ?? 0} onChange={(v) => setEd(p => ({ ...p, experience: Number(v) }))} />
            <NumberInput label="Gold" value={ed.gold as number ?? 0} onChange={(v) => setEd(p => ({ ...p, gold: Number(v) }))} />
            <TextInput label="Guild Id" value={(ed.guild_id ?? '') as string} onChange={(e) => setEd(p => ({ ...p, guild_id: e.currentTarget.value }))} />
            <TextInput label="Guild Name" value={(ed.guild_name ?? '') as string} onChange={(e) => setEd(p => ({ ...p, guild_name: e.currentTarget.value }))} />
            <TextInput label="Special Ability" value={(ed.special_ability ?? '') as string} onChange={(e) => setEd(p => ({ ...p, special_ability: e.currentTarget.value }))} />
            <TextInput label="Equipments (comma-separated)" value={(ed.equipments as string[] || []).join(', ')} onChange={(e) => setEd(p => ({ ...p, equipments: e.currentTarget.value.split(',').map(s => s.trim()).filter(Boolean) }))} />
            <TextInput label="Created At" value={(ed.created_at ?? '') as string} onChange={(e) => setEd(p => ({ ...p, created_at: e.currentTarget.value }))} />
            <Group justify="flex-end">
              <Button variant="light" onClick={closeEdit}>Cancel</Button>
              <Button onClick={handleUpdate} loading={saving}>Save</Button>
            </Group>
          </Stack>
        </Modal>
      </Stack>
    </Container>
  );
}
