// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, useNavigate, Link } from '@tanstack/react-router';
import { useState } from 'react';
import {
  Container, Title, Group, Button, Stack, TextInput, NumberInput,
  Select, Checkbox, Textarea, Card, Alert,
} from '@mantine/core';
import { IconArrowLeft } from '@tabler/icons-react';
import { characterApi } from '../../generated/api/characterApi';
import type { Character } from '../../generated/types';

export const Route = createFileRoute('/character/create')({
  component: CreatePage,
});

function CreatePage() {
  const navigate = useNavigate();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [fd, setFd] = useState<Record<string, any>>({"name":"","character_class":"","valueAD__x":0,"level":0,"hp":0,"mp":0,"attack":0,"defense":0,"experience":0,"gold":0,"guild_id":"","guild_name":"","special_ability":"","equipments":[],"created_at":""});
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const result = await characterApi.create(fd as unknown as Character);
      navigate({ to: '/character/$resourceId', params: { resourceId: result.data.resource_id } });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to create');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Container size="md" py="xl">
      <Stack gap="md">
        <Group>
          <Button variant="subtle" component={Link} to="/character" leftSection={<IconArrowLeft size={16} />}>Back</Button>
          <Title order={2}>Create Character</Title>
        </Group>
        {error && <Alert color="red" title="Error">{error}</Alert>}
        <Card shadow="sm" padding="lg" radius="md" withBorder>
          <Stack gap="md">
        <TextInput label="Name" value={(fd.name ?? '') as string} onChange={(e) => setFd(p => ({ ...p, name: e.currentTarget.value }))} required />
        <Select label="Character Class" data={["⚔️ 戰士", "🏹 弓箭手", "💾 數據守護者", "🔮 法師"]} value={fd.character_class as string} onChange={(v) => setFd(p => ({ ...p, character_class: v ?? '' }))} required />
        <NumberInput label="ValueAD X" value={fd.valueAD__x as number} onChange={(v) => setFd(p => ({ ...p, valueAD__x: Number(v) }))} />
        <NumberInput label="Level" value={fd.level as number} onChange={(v) => setFd(p => ({ ...p, level: Number(v) }))} />
        <NumberInput label="Hp" value={fd.hp as number} onChange={(v) => setFd(p => ({ ...p, hp: Number(v) }))} />
        <NumberInput label="Mp" value={fd.mp as number} onChange={(v) => setFd(p => ({ ...p, mp: Number(v) }))} />
        <NumberInput label="Attack" value={fd.attack as number} onChange={(v) => setFd(p => ({ ...p, attack: Number(v) }))} />
        <NumberInput label="Defense" value={fd.defense as number} onChange={(v) => setFd(p => ({ ...p, defense: Number(v) }))} />
        <NumberInput label="Experience" value={fd.experience as number} onChange={(v) => setFd(p => ({ ...p, experience: Number(v) }))} />
        <NumberInput label="Gold" value={fd.gold as number} onChange={(v) => setFd(p => ({ ...p, gold: Number(v) }))} />
        <TextInput label="Guild Id" value={(fd.guild_id ?? '') as string} onChange={(e) => setFd(p => ({ ...p, guild_id: e.currentTarget.value }))} />
        <TextInput label="Guild Name" value={(fd.guild_name ?? '') as string} onChange={(e) => setFd(p => ({ ...p, guild_name: e.currentTarget.value }))} />
        <TextInput label="Special Ability" value={(fd.special_ability ?? '') as string} onChange={(e) => setFd(p => ({ ...p, special_ability: e.currentTarget.value }))} />
        <TextInput label="Equipments (comma-separated)" value={(fd.equipments as string[] || []).join(', ')} onChange={(e) => setFd(p => ({ ...p, equipments: e.currentTarget.value.split(',').map(s => s.trim()).filter(Boolean) }))} />
        <TextInput label="Created At" value={(fd.created_at ?? '') as string} onChange={(e) => setFd(p => ({ ...p, created_at: e.currentTarget.value }))} />
            <Group justify="flex-end" mt="md">
              <Button variant="light" component={Link} to="/character">Cancel</Button>
              <Button onClick={handleSubmit} loading={submitting}>Create</Button>
            </Group>
          </Stack>
        </Card>
      </Stack>
    </Container>
  );
}
