// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useEffect, useState, useMemo, useCallback } from 'react';
import { Container, Title, Group, Button, Stack, Text } from '@mantine/core';
import { IconPlus, IconRefresh } from '@tabler/icons-react';
import {
  MantineReactTable, useMantineReactTable,
  type MRT_ColumnDef, type MRT_PaginationState, type MRT_SortingState,
} from 'mantine-react-table';
import { characterApi } from '../../generated/api/characterApi';
import type { Character } from '../../generated/types';
import type { FullResource } from '../../types/api';

type Row = FullResource<Character>;

export const Route = createFileRoute('/character/')({
  component: ListPage,
});

function ListPage() {
  const navigate = useNavigate();
  const [data, setData] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState<MRT_PaginationState>({ pageIndex: 0, pageSize: 20 });
  const [sorting, setSorting] = useState<MRT_SortingState>([]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const sorts = sorting.length
        ? JSON.stringify(sorting.map(s => ({ type: 'data', field_path: s.id, direction: s.desc ? '-' : '+' })))
        : undefined;
      const [list, cnt] = await Promise.all([
        characterApi.listFull({
          limit: pagination.pageSize,
          offset: pagination.pageIndex * pagination.pageSize,
          sorts,
        }),
        characterApi.count(),
      ]);
      setData(list.data);
      setTotal(cnt.data);
    } catch (e) {
      console.error('fetch error', e);
    } finally {
      setLoading(false);
    }
  }, [pagination, sorting]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const columns = useMemo<MRT_ColumnDef<Row>[]>(() => [
    {
      id: 'resource_id',
      header: 'Resource ID',
      accessorFn: (row: Row) => row?.meta?.resource_id,
      size: 220,
    },
    {
      id: 'name',
      header: 'Name',
      accessorFn: (row: Row) => row?.data?.name,
    },
    {
      id: 'character_class',
      header: 'Character Class',
      accessorFn: (row: Row) => row?.data?.character_class,
    },
    {
      id: 'valueAD__x',
      header: 'ValueAD X',
      accessorFn: (row: Row) => row?.data?.valueAD__x,
    },
    {
      id: 'level',
      header: 'Level',
      accessorFn: (row: Row) => row?.data?.level,
    },
    {
      id: 'hp',
      header: 'Hp',
      accessorFn: (row: Row) => row?.data?.hp,
    },
    {
      id: 'mp',
      header: 'Mp',
      accessorFn: (row: Row) => row?.data?.mp,
    },
    {
      id: 'attack',
      header: 'Attack',
      accessorFn: (row: Row) => row?.data?.attack,
    },
    {
      id: 'defense',
      header: 'Defense',
      accessorFn: (row: Row) => row?.data?.defense,
    },
    {
      id: 'experience',
      header: 'Experience',
      accessorFn: (row: Row) => row?.data?.experience,
    },
    {
      id: 'gold',
      header: 'Gold',
      accessorFn: (row: Row) => row?.data?.gold,
    },
    {
      id: 'guild_id',
      header: 'Guild Id',
      accessorFn: (row: Row) => row?.data?.guild_id,
    },
    {
      id: 'guild_name',
      header: 'Guild Name',
      accessorFn: (row: Row) => row?.data?.guild_name,
    },
    {
      id: 'special_ability',
      header: 'Special Ability',
      accessorFn: (row: Row) => row?.data?.special_ability,
    },
    {
      id: 'created_at',
      header: 'Created At',
      accessorFn: (row: Row) => row?.data?.created_at,
    },
    {
      id: 'updated_time',
      header: 'Updated',
      accessorFn: (row: Row) => row?.meta?.updated_time,
      Cell: ({ cell }) => new Date(cell.getValue<string>()).toLocaleString(),
    },
  ], []);

  const table = useMantineReactTable({
    columns,
    data,
    manualPagination: true,
    manualSorting: true,
    rowCount: total,
    state: { isLoading: loading, pagination, sorting },
    onPaginationChange: setPagination,
    onSortingChange: setSorting,
    mantineTableBodyRowProps: ({ row }) => ({
      onClick: () => navigate({
        to: '/character/$resourceId',
        params: { resourceId: row.original?.meta?.resource_id ?? '' },
      }),
      style: { cursor: 'pointer' },
    }),
    initialState: { density: 'xs' },
  });

  return (
    <Container size="xl" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <div>
            <Title order={2}>Character</Title>
            <Text c="dimmed" size="sm">{total} total resources</Text>
          </div>
          <Group>
            <Button variant="light" leftSection={<IconRefresh size={16} />} onClick={fetchData}>Refresh</Button>
            <Button leftSection={<IconPlus size={16} />} component={Link} to="/character/create">Create</Button>
          </Group>
        </Group>
        <MantineReactTable table={table} />
      </Stack>
    </Container>
  );
}
