// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceDetail } from '../../../lib/components/ResourceDetail';
import { getResource } from '../../../lib/resources';
import type { Guild } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/guild/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const config = getResource('guild')!;
  return <ResourceDetail<Guild> config={config} resourceId={resourceId} basePath="/autocrud-admin/guild" />;
}
