// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../lib/components/ResourceCreate';
import { getResource } from '../../../lib/resources';
import type { Guild } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/guild/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('guild')!;
  return <ResourceCreate<Guild> config={config} basePath="/autocrud-admin/guild" />;
}
