// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceTable } from '../../../lib/components/ResourceTable';
import { getResource } from '../../../lib/resources';
import type { Guild } from '../../../generated/types';

export const Route = createFileRoute('/autocrud-admin/guild/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('guild')!;
  return <ResourceTable<Guild> config={config} basePath="/autocrud-admin/guild" />;
}
