// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@mantine/core';
import { ResourceTable } from '../../../specstar/lib/components/ResourceTable';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/guild/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('guild')!;
  return (
    <Container size="xl" py="xl">
      <ResourceTable config={config} basePath="/specstar-admin/guild" />
    </Container>
  );
}
