// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';
import type { CreateNewCharacter4CharacterJob } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/create-new-character4-job/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('create-new-character4-job')!;
  return (
    <ResourceCreate<CreateNewCharacter4CharacterJob>
      config={config}
      basePath="/autocrud-admin/create-new-character4-job"
    />
  );
}
