// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/create-new-character2-job/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('create-new-character2-job')!;
  return <ResourceCreate config={config} basePath="/autocrud-admin/create-new-character2-job" />;
}
