// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import {
  Container, Title, Group, Button, Stack, Text, Card, Badge,
  Grid, Loader, Alert, Modal, TextInput, NumberInput, Select,
  Checkbox, Textarea, Table, ActionIcon, Tooltip,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconEdit, IconTrash, IconArrowLeft, IconHistory, IconRestore } from '@tabler/icons-react';
import { guildApi } from '../../generated/api/guildApi';
import type { Guild } from '../../generated/types';
import type { FullResource, RevisionInfo } from '../../types/api';

export const Route = createFileRoute('/guild/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const [res, setRes] = useState<FullResource<Guild> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editOpen, { open: openEdit, close: closeEdit }] = useDisclosure(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [ed, setEd] = useState<Record<string, any>>({});
  const [saving, setSaving] = useState(false);
  const [revisions, setRevisions] = useState<RevisionInfo[]>([]);
  const [showRev, { toggle: toggleRev }] = useDisclosure(false);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const r = await guildApi.getFull(resourceId);
      setRes(r.data);
      setEd({ ...(r.data.data as Record<string, unknown>) });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [resourceId]);

  const handleUpdate = async () => {
    setSaving(true);
    try {
      await guildApi.update(resourceId, ed as unknown as Guild);
      closeEdit();
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Update failed');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm('Delete this resource?')) return;
    try {
      await guildApi.delete(resourceId);
      window.history.back();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Delete failed');
    }
  };

  const handleRestore = async () => {
    try {
      await guildApi.restore(resourceId);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Restore failed');
    }
  };

  const loadRevisions = async () => {
    try {
      const r = await guildApi.revisionList(resourceId);
      setRevisions(r.data.revisions);
    } catch (e) { console.error(e); }
  };

  if (loading) return <Container size="lg" py="xl"><Loader /></Container>;
  if (error || !res) return <Container size="lg" py="xl"><Alert color="red" title="Error">{error || 'Not found'}</Alert></Container>;

  const { data, meta, revision_info } = res;

  return (
    <Container size="lg" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <Group>
            <Button variant="subtle" component={Link} to="/guild" leftSection={<IconArrowLeft size={16} />}>Back</Button>
            <Title order={2}>Guild</Title>
            <Badge color={revision_info.status === 'stable' ? 'green' : 'yellow'}>{revision_info.status}</Badge>
          </Group>
          <Group>
            {meta.is_deleted && <Button color="green" leftSection={<IconRestore size={16} />} onClick={handleRestore}>Restore</Button>}
            <Button variant="light" leftSection={<IconHistory size={16} />} onClick={() => { toggleRev(); if (!showRev) loadRevisions(); }}>Revisions</Button>
            <Button variant="light" leftSection={<IconEdit size={16} />} onClick={openEdit}>Edit</Button>
            <Button color="red" variant="light" leftSection={<IconTrash size={16} />} onClick={handleDelete}>Delete</Button>
          </Group>
        </Group>

        {meta.is_deleted && <Alert color="red" title="Deleted">This resource has been deleted.</Alert>}

        <Grid>
          <Grid.Col span={{ base: 12, md: 8 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Data</Title>
              <Stack gap="sm">
              <div><Text size="sm" fw={500} c="dimmed">Name</Text><Text>{data.name != null ? String(data.name) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Description</Text><Text>{data.description != null ? String(data.description) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Leader</Text><Text>{data.leader != null ? String(data.leader) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Member Count</Text><Text>{data.member_count != null ? String(data.member_count) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Level</Text><Text>{data.level != null ? String(data.level) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Treasury</Text><Text>{data.treasury != null ? String(data.treasury) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Founded At</Text><Text>{data.founded_at != null ? String(data.founded_at) : '-'}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
          <Grid.Col span={{ base: 12, md: 4 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Metadata</Title>
              <Stack gap="xs">
                <div><Text size="sm" fw={500} c="dimmed">Resource ID</Text><Text size="sm" style={{ wordBreak: 'break-all' }}>{meta.resource_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Revision</Text><Text size="sm">{meta.current_revision_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Total Revisions</Text><Badge>{meta.total_revision_count}</Badge></div>
                <div><Text size="sm" fw={500} c="dimmed">Created</Text><Text size="sm">{new Date(meta.created_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Updated</Text><Text size="sm">{new Date(meta.updated_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Created By</Text><Text size="sm">{meta.created_by}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
        </Grid>

        {showRev && (
          <Card shadow="sm" padding="lg" radius="md" withBorder>
            <Title order={4} mb="md">Revision History</Title>
            <Table striped highlightOnHover>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th>Revision ID</Table.Th>
                  <Table.Th>Status</Table.Th>
                  <Table.Th>Schema Ver</Table.Th>
                  <Table.Th>Hash</Table.Th>
                  <Table.Th>Action</Table.Th>
                </Table.Tr>
              </Table.Thead>
              <Table.Tbody>
                {revisions.map((rev) => (
                  <Table.Tr key={rev.uid}>
                    <Table.Td>{rev.revision_id}</Table.Td>
                    <Table.Td><Badge color={rev.status === 'stable' ? 'green' : 'yellow'}>{rev.status}</Badge></Table.Td>
                    <Table.Td>{rev.schema_version || '-'}</Table.Td>
                    <Table.Td><Text size="xs" ff="monospace">{rev.data_hash.slice(0, 12)}...</Text></Table.Td>
                    <Table.Td>
                      <Tooltip label="Switch to revision">
                        <ActionIcon variant="light" size="sm" onClick={async () => { await guildApi.switchRevision(resourceId, rev.revision_id); await load(); await loadRevisions(); }}>
                          <IconRestore size={14} />
                        </ActionIcon>
                      </Tooltip>
                    </Table.Td>
                  </Table.Tr>
                ))}
              </Table.Tbody>
            </Table>
          </Card>
        )}

        <Modal opened={editOpen} onClose={closeEdit} title="Edit Guild" size="lg">
          <Stack gap="md">
            <TextInput label="Name" value={(ed.name ?? '') as string} onChange={(e) => setEd(p => ({ ...p, name: e.currentTarget.value }))} required />
            <Textarea label="Description" value={(ed.description ?? '') as string} onChange={(e) => setEd(p => ({ ...p, description: e.currentTarget.value }))} required autosize minRows={3} />
            <TextInput label="Leader" value={(ed.leader ?? '') as string} onChange={(e) => setEd(p => ({ ...p, leader: e.currentTarget.value }))} required />
            <NumberInput label="Member Count" value={ed.member_count as number ?? 0} onChange={(v) => setEd(p => ({ ...p, member_count: Number(v) }))} />
            <NumberInput label="Level" value={ed.level as number ?? 0} onChange={(v) => setEd(p => ({ ...p, level: Number(v) }))} />
            <NumberInput label="Treasury" value={ed.treasury as number ?? 0} onChange={(v) => setEd(p => ({ ...p, treasury: Number(v) }))} />
            <TextInput label="Founded At" value={(ed.founded_at ?? '') as string} onChange={(e) => setEd(p => ({ ...p, founded_at: e.currentTarget.value }))} />
            <Group justify="flex-end">
              <Button variant="light" onClick={closeEdit}>Cancel</Button>
              <Button onClick={handleUpdate} loading={saving}>Save</Button>
            </Group>
          </Stack>
        </Modal>
      </Stack>
    </Container>
  );
}
