// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, useNavigate, Link } from '@tanstack/react-router';
import { useState } from 'react';
import {
  Container, Title, Group, Button, Stack, TextInput, NumberInput,
  Select, Checkbox, Textarea, Card, Alert,
} from '@mantine/core';
import { IconArrowLeft } from '@tabler/icons-react';
import { guildApi } from '../../generated/api/guildApi';
import type { Guild } from '../../generated/types';

export const Route = createFileRoute('/guild/create')({
  component: CreatePage,
});

function CreatePage() {
  const navigate = useNavigate();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [fd, setFd] = useState<Record<string, any>>({"name":"","description":"","leader":"","member_count":0,"level":0,"treasury":0,"founded_at":""});
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const result = await guildApi.create(fd as unknown as Guild);
      navigate({ to: '/guild/$resourceId', params: { resourceId: result.data.resource_id } });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to create');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Container size="md" py="xl">
      <Stack gap="md">
        <Group>
          <Button variant="subtle" component={Link} to="/guild" leftSection={<IconArrowLeft size={16} />}>Back</Button>
          <Title order={2}>Create Guild</Title>
        </Group>
        {error && <Alert color="red" title="Error">{error}</Alert>}
        <Card shadow="sm" padding="lg" radius="md" withBorder>
          <Stack gap="md">
        <TextInput label="Name" value={(fd.name ?? '') as string} onChange={(e) => setFd(p => ({ ...p, name: e.currentTarget.value }))} required />
        <Textarea label="Description" value={(fd.description ?? '') as string} onChange={(e) => setFd(p => ({ ...p, description: e.currentTarget.value }))} required autosize minRows={3} />
        <TextInput label="Leader" value={(fd.leader ?? '') as string} onChange={(e) => setFd(p => ({ ...p, leader: e.currentTarget.value }))} required />
        <NumberInput label="Member Count" value={fd.member_count as number} onChange={(v) => setFd(p => ({ ...p, member_count: Number(v) }))} />
        <NumberInput label="Level" value={fd.level as number} onChange={(v) => setFd(p => ({ ...p, level: Number(v) }))} />
        <NumberInput label="Treasury" value={fd.treasury as number} onChange={(v) => setFd(p => ({ ...p, treasury: Number(v) }))} />
        <TextInput label="Founded At" value={(fd.founded_at ?? '') as string} onChange={(e) => setFd(p => ({ ...p, founded_at: e.currentTarget.value }))} />
            <Group justify="flex-end" mt="md">
              <Button variant="light" component={Link} to="/guild">Cancel</Button>
              <Button onClick={handleSubmit} loading={submitting}>Create</Button>
            </Group>
          </Stack>
        </Card>
      </Stack>
    </Container>
  );
}
