// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';
import type { NewCharacterJob } from '../../../autocrud/generated/types';

export const Route = createFileRoute('/autocrud-admin/new-char1-job/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('new-char1-job')!;
  return <ResourceCreate<NewCharacterJob> config={config} basePath="/autocrud-admin/new-char1-job" />;
}
