// Auto-generated by SpecStar Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../specstar/lib/components/ResourceCreate';
import { getResource } from '../../../specstar/lib/resources';

export const Route = createFileRoute('/specstar-admin/quest/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('quest')!;
  return <ResourceCreate config={config} basePath="/specstar-admin/quest" />;
}
