// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import {
  Container, Title, Group, Button, Stack, Text, Card, Badge,
  Grid, Loader, Alert, Modal, TextInput, NumberInput, Select,
  Checkbox, Textarea, Table, ActionIcon, Tooltip,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconEdit, IconTrash, IconArrowLeft, IconHistory, IconRestore } from '@tabler/icons-react';
import { equipmentApi } from '../../generated/api/equipmentApi';
import type { Equipment } from '../../generated/types';
import type { FullResource, RevisionInfo } from '../../types/api';

export const Route = createFileRoute('/equipment/$resourceId')({
  component: DetailPage,
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const [res, setRes] = useState<FullResource<Equipment> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editOpen, { open: openEdit, close: closeEdit }] = useDisclosure(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [ed, setEd] = useState<Record<string, any>>({});
  const [saving, setSaving] = useState(false);
  const [revisions, setRevisions] = useState<RevisionInfo[]>([]);
  const [showRev, { toggle: toggleRev }] = useDisclosure(false);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const r = await equipmentApi.getFull(resourceId);
      setRes(r.data);
      setEd({ ...(r.data.data as Record<string, unknown>) });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [resourceId]);

  const handleUpdate = async () => {
    setSaving(true);
    try {
      await equipmentApi.update(resourceId, ed as unknown as Equipment);
      closeEdit();
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Update failed');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm('Delete this resource?')) return;
    try {
      await equipmentApi.delete(resourceId);
      window.history.back();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Delete failed');
    }
  };

  const handleRestore = async () => {
    try {
      await equipmentApi.restore(resourceId);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Restore failed');
    }
  };

  const loadRevisions = async () => {
    try {
      const r = await equipmentApi.revisionList(resourceId);
      setRevisions(r.data.revisions);
    } catch (e) { console.error(e); }
  };

  if (loading) return <Container size="lg" py="xl"><Loader /></Container>;
  if (error || !res) return <Container size="lg" py="xl"><Alert color="red" title="Error">{error || 'Not found'}</Alert></Container>;

  const { data, meta, revision_info } = res;

  return (
    <Container size="lg" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <Group>
            <Button variant="subtle" component={Link} to="/equipment" leftSection={<IconArrowLeft size={16} />}>Back</Button>
            <Title order={2}>Equipment</Title>
            <Badge color={revision_info.status === 'stable' ? 'green' : 'yellow'}>{revision_info.status}</Badge>
          </Group>
          <Group>
            {meta.is_deleted && <Button color="green" leftSection={<IconRestore size={16} />} onClick={handleRestore}>Restore</Button>}
            <Button variant="light" leftSection={<IconHistory size={16} />} onClick={() => { toggleRev(); if (!showRev) loadRevisions(); }}>Revisions</Button>
            <Button variant="light" leftSection={<IconEdit size={16} />} onClick={openEdit}>Edit</Button>
            <Button color="red" variant="light" leftSection={<IconTrash size={16} />} onClick={handleDelete}>Delete</Button>
          </Group>
        </Group>

        {meta.is_deleted && <Alert color="red" title="Deleted">This resource has been deleted.</Alert>}

        <Grid>
          <Grid.Col span={{ base: 12, md: 8 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Data</Title>
              <Stack gap="sm">
              <div><Text size="sm" fw={500} c="dimmed">Name</Text><Text>{data.name != null ? String(data.name) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Rarity</Text><Text>{data.rarity != null ? String(data.rarity) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Character Class Req</Text><Text>{data.character_class_req != null ? String(data.character_class_req) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Attack Bonus</Text><Text>{data.attack_bonus != null ? String(data.attack_bonus) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Defense Bonus</Text><Text>{data.defense_bonus != null ? String(data.defense_bonus) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Special Effects</Text><Group gap="xs">{(data.special_effects || []).map((v: string, i: number) => <Badge key={i} variant="light">{String(v)}</Badge>)}</Group></div>
              <div><Text size="sm" fw={500} c="dimmed">Price</Text><Text>{data.price != null ? String(data.price) : '-'}</Text></div>
              <div><Text size="sm" fw={500} c="dimmed">Icon</Text><Text>{data.icon ? 'Binary data' : '-'}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
          <Grid.Col span={{ base: 12, md: 4 }}>
            <Card shadow="sm" padding="lg" radius="md" withBorder>
              <Title order={4} mb="md">Metadata</Title>
              <Stack gap="xs">
                <div><Text size="sm" fw={500} c="dimmed">Resource ID</Text><Text size="sm" style={{ wordBreak: 'break-all' }}>{meta.resource_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Revision</Text><Text size="sm">{meta.current_revision_id}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Total Revisions</Text><Badge>{meta.total_revision_count}</Badge></div>
                <div><Text size="sm" fw={500} c="dimmed">Created</Text><Text size="sm">{new Date(meta.created_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Updated</Text><Text size="sm">{new Date(meta.updated_time).toLocaleString()}</Text></div>
                <div><Text size="sm" fw={500} c="dimmed">Created By</Text><Text size="sm">{meta.created_by}</Text></div>
              </Stack>
            </Card>
          </Grid.Col>
        </Grid>

        {showRev && (
          <Card shadow="sm" padding="lg" radius="md" withBorder>
            <Title order={4} mb="md">Revision History</Title>
            <Table striped highlightOnHover>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th>Revision ID</Table.Th>
                  <Table.Th>Status</Table.Th>
                  <Table.Th>Schema Ver</Table.Th>
                  <Table.Th>Hash</Table.Th>
                  <Table.Th>Action</Table.Th>
                </Table.Tr>
              </Table.Thead>
              <Table.Tbody>
                {revisions.map((rev) => (
                  <Table.Tr key={rev.uid}>
                    <Table.Td>{rev.revision_id}</Table.Td>
                    <Table.Td><Badge color={rev.status === 'stable' ? 'green' : 'yellow'}>{rev.status}</Badge></Table.Td>
                    <Table.Td>{rev.schema_version || '-'}</Table.Td>
                    <Table.Td><Text size="xs" ff="monospace">{rev.data_hash.slice(0, 12)}...</Text></Table.Td>
                    <Table.Td>
                      <Tooltip label="Switch to revision">
                        <ActionIcon variant="light" size="sm" onClick={async () => { await equipmentApi.switchRevision(resourceId, rev.revision_id); await load(); await loadRevisions(); }}>
                          <IconRestore size={14} />
                        </ActionIcon>
                      </Tooltip>
                    </Table.Td>
                  </Table.Tr>
                ))}
              </Table.Tbody>
            </Table>
          </Card>
        )}

        <Modal opened={editOpen} onClose={closeEdit} title="Edit Equipment" size="lg">
          <Stack gap="md">
            <TextInput label="Name" value={(ed.name ?? '') as string} onChange={(e) => setEd(p => ({ ...p, name: e.currentTarget.value }))} required />
            <Select label="Rarity" data={["傳奇", "史詩", "普通", "稀有", "🚀 AutoCRUD 神器"]} value={ed.rarity as string ?? ''} onChange={(v) => setEd(p => ({ ...p, rarity: v ?? '' }))} required />
            <Select label="Character Class Req" data={["⚔️ 戰士", "🏹 弓箭手", "💾 數據守護者", "🔮 法師"]} value={ed.character_class_req as string ?? ''} onChange={(v) => setEd(p => ({ ...p, character_class_req: v ?? '' }))} />
            <NumberInput label="Attack Bonus" value={ed.attack_bonus as number ?? 0} onChange={(v) => setEd(p => ({ ...p, attack_bonus: Number(v) }))} />
            <NumberInput label="Defense Bonus" value={ed.defense_bonus as number ?? 0} onChange={(v) => setEd(p => ({ ...p, defense_bonus: Number(v) }))} />
            <TextInput label="Special Effects (comma-separated)" value={(ed.special_effects as string[] || []).join(', ')} onChange={(e) => setEd(p => ({ ...p, special_effects: e.currentTarget.value.split(',').map(s => s.trim()).filter(Boolean) }))} />
            <NumberInput label="Price" value={ed.price as number ?? 0} onChange={(v) => setEd(p => ({ ...p, price: Number(v) }))} />
            <Group justify="flex-end">
              <Button variant="light" onClick={closeEdit}>Cancel</Button>
              <Button onClick={handleUpdate} loading={saving}>Save</Button>
            </Group>
          </Stack>
        </Modal>
      </Stack>
    </Container>
  );
}
