// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, useNavigate, Link } from '@tanstack/react-router';
import { useState } from 'react';
import {
  Container, Title, Group, Button, Stack, TextInput, NumberInput,
  Select, Checkbox, Textarea, Card, Alert,
} from '@mantine/core';
import { IconArrowLeft } from '@tabler/icons-react';
import { equipmentApi } from '../../generated/api/equipmentApi';
import type { Equipment } from '../../generated/types';

export const Route = createFileRoute('/equipment/create')({
  component: CreatePage,
});

function CreatePage() {
  const navigate = useNavigate();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [fd, setFd] = useState<Record<string, any>>({"name":"","rarity":"","character_class_req":"","attack_bonus":0,"defense_bonus":0,"special_effects":[],"price":0});
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const result = await equipmentApi.create(fd as unknown as Equipment);
      navigate({ to: '/equipment/$resourceId', params: { resourceId: result.data.resource_id } });
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to create');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Container size="md" py="xl">
      <Stack gap="md">
        <Group>
          <Button variant="subtle" component={Link} to="/equipment" leftSection={<IconArrowLeft size={16} />}>Back</Button>
          <Title order={2}>Create Equipment</Title>
        </Group>
        {error && <Alert color="red" title="Error">{error}</Alert>}
        <Card shadow="sm" padding="lg" radius="md" withBorder>
          <Stack gap="md">
        <TextInput label="Name" value={(fd.name ?? '') as string} onChange={(e) => setFd(p => ({ ...p, name: e.currentTarget.value }))} required />
        <Select label="Rarity" data={["傳奇", "史詩", "普通", "稀有", "🚀 AutoCRUD 神器"]} value={fd.rarity as string} onChange={(v) => setFd(p => ({ ...p, rarity: v ?? '' }))} required />
        <Select label="Character Class Req" data={["⚔️ 戰士", "🏹 弓箭手", "💾 數據守護者", "🔮 法師"]} value={fd.character_class_req as string} onChange={(v) => setFd(p => ({ ...p, character_class_req: v ?? '' }))} />
        <NumberInput label="Attack Bonus" value={fd.attack_bonus as number} onChange={(v) => setFd(p => ({ ...p, attack_bonus: Number(v) }))} />
        <NumberInput label="Defense Bonus" value={fd.defense_bonus as number} onChange={(v) => setFd(p => ({ ...p, defense_bonus: Number(v) }))} />
        <TextInput label="Special Effects (comma-separated)" value={(fd.special_effects as string[] || []).join(', ')} onChange={(e) => setFd(p => ({ ...p, special_effects: e.currentTarget.value.split(',').map(s => s.trim()).filter(Boolean) }))} />
        <NumberInput label="Price" value={fd.price as number} onChange={(v) => setFd(p => ({ ...p, price: Number(v) }))} />
            <Group justify="flex-end" mt="md">
              <Button variant="light" component={Link} to="/equipment">Cancel</Button>
              <Button onClick={handleSubmit} loading={submitting}>Create</Button>
            </Group>
          </Stack>
        </Card>
      </Stack>
    </Container>
  );
}
