// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useEffect, useState, useMemo, useCallback } from 'react';
import { Container, Title, Group, Button, Stack, Text } from '@mantine/core';
import { IconPlus, IconRefresh } from '@tabler/icons-react';
import {
  MantineReactTable, useMantineReactTable,
  type MRT_ColumnDef, type MRT_PaginationState, type MRT_SortingState,
} from 'mantine-react-table';
import { equipmentApi } from '../../generated/api/equipmentApi';
import type { Equipment } from '../../generated/types';
import type { FullResource } from '../../types/api';

type Row = FullResource<Equipment>;

export const Route = createFileRoute('/equipment/')({
  component: ListPage,
});

function ListPage() {
  const navigate = useNavigate();
  const [data, setData] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState<MRT_PaginationState>({ pageIndex: 0, pageSize: 20 });
  const [sorting, setSorting] = useState<MRT_SortingState>([]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const sorts = sorting.length
        ? JSON.stringify(sorting.map(s => ({ type: 'data', field_path: s.id, direction: s.desc ? '-' : '+' })))
        : undefined;
      const [list, cnt] = await Promise.all([
        equipmentApi.listFull({
          limit: pagination.pageSize,
          offset: pagination.pageIndex * pagination.pageSize,
          sorts,
        }),
        equipmentApi.count(),
      ]);
      setData(list.data);
      setTotal(cnt.data);
    } catch (e) {
      console.error('fetch error', e);
    } finally {
      setLoading(false);
    }
  }, [pagination, sorting]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const columns = useMemo<MRT_ColumnDef<Row>[]>(() => [
    {
      id: 'resource_id',
      header: 'Resource ID',
      accessorFn: (row: Row) => row?.meta?.resource_id,
      size: 220,
    },
    {
      id: 'name',
      header: 'Name',
      accessorFn: (row: Row) => row?.data?.name,
    },
    {
      id: 'rarity',
      header: 'Rarity',
      accessorFn: (row: Row) => row?.data?.rarity,
    },
    {
      id: 'character_class_req',
      header: 'Character Class Req',
      accessorFn: (row: Row) => row?.data?.character_class_req,
    },
    {
      id: 'attack_bonus',
      header: 'Attack Bonus',
      accessorFn: (row: Row) => row?.data?.attack_bonus,
    },
    {
      id: 'defense_bonus',
      header: 'Defense Bonus',
      accessorFn: (row: Row) => row?.data?.defense_bonus,
    },
    {
      id: 'price',
      header: 'Price',
      accessorFn: (row: Row) => row?.data?.price,
    },
    {
      id: 'updated_time',
      header: 'Updated',
      accessorFn: (row: Row) => row?.meta?.updated_time,
      Cell: ({ cell }) => new Date(cell.getValue<string>()).toLocaleString(),
    },
  ], []);

  const table = useMantineReactTable({
    columns,
    data,
    manualPagination: true,
    manualSorting: true,
    rowCount: total,
    state: { isLoading: loading, pagination, sorting },
    onPaginationChange: setPagination,
    onSortingChange: setSorting,
    mantineTableBodyRowProps: ({ row }) => ({
      onClick: () => navigate({
        to: '/equipment/$resourceId',
        params: { resourceId: row.original?.meta?.resource_id ?? '' },
      }),
      style: { cursor: 'pointer' },
    }),
    initialState: { density: 'xs' },
  });

  return (
    <Container size="xl" py="xl">
      <Stack gap="md">
        <Group justify="space-between">
          <div>
            <Title order={2}>Equipment</Title>
            <Text c="dimmed" size="sm">{total} total resources</Text>
          </div>
          <Group>
            <Button variant="light" leftSection={<IconRefresh size={16} />} onClick={fetchData}>Refresh</Button>
            <Button leftSection={<IconPlus size={16} />} component={Link} to="/equipment/create">Create</Button>
          </Group>
        </Group>
        <MantineReactTable table={table} />
      </Stack>
    </Container>
  );
}
